MUSL_SUBDIR   = source/musl
MUSL_OBJDIR   = $(OBJDIR)/musl
MUSL_LIBC     = $(LIBDIR)/libc.a
MUSL_CFLAGS   = -std=c99 -nostdinc -D_XOPEN_SOURCE=700 -Os -pipe -include vis.h
MUSL_CPPFLAGS =
MUSL_COMPILE = $(CC) $(MUSL_CFLAGS) $(MUSL_INCS) $(MUSL_CPPFLAGS) -c -o $@ $<

PHONY  += libc
ECLEAN += $(MUSL_LIBC) $(MUSL_CRT_OBJS) $(MUSL_OBJS)
DIRS   += \
    $(MUSL_OBJDIR)/crt \
    $(MUSL_OBJDIR)/crt/x86_64 \
    $(MUSL_OBJDIR)/include \
    $(MUSL_OBJDIR)/include/bits \
    $(MUSL_OBJDIR)/ldso \
    $(MUSL_OBJDIR)/src/aio \
    $(MUSL_OBJDIR)/src/complex \
    $(MUSL_OBJDIR)/src/conf \
    $(MUSL_OBJDIR)/src/crypt \
    $(MUSL_OBJDIR)/src/ctype \
    $(MUSL_OBJDIR)/src/dirent \
    $(MUSL_OBJDIR)/src/env \
    $(MUSL_OBJDIR)/src/errno \
    $(MUSL_OBJDIR)/src/exit \
    $(MUSL_OBJDIR)/src/fcntl \
    $(MUSL_OBJDIR)/src/fenv \
    $(MUSL_OBJDIR)/src/fenv/x86_64 \
    $(MUSL_OBJDIR)/src/internal \
    $(MUSL_OBJDIR)/src/internal/x86_64 \
    $(MUSL_OBJDIR)/src/ipc \
    $(MUSL_OBJDIR)/src/ldso \
    $(MUSL_OBJDIR)/src/ldso/x86_64 \
    $(MUSL_OBJDIR)/src/legacy \
    $(MUSL_OBJDIR)/src/linux \
    $(MUSL_OBJDIR)/src/locale \
    $(MUSL_OBJDIR)/src/malloc \
    $(MUSL_OBJDIR)/src/math \
    $(MUSL_OBJDIR)/src/math/x86_64 \
    $(MUSL_OBJDIR)/src/misc \
    $(MUSL_OBJDIR)/src/mman \
    $(MUSL_OBJDIR)/src/mq \
    $(MUSL_OBJDIR)/src/multibyte \
    $(MUSL_OBJDIR)/src/network \
    $(MUSL_OBJDIR)/src/passwd \
    $(MUSL_OBJDIR)/src/prng \
    $(MUSL_OBJDIR)/src/process \
    $(MUSL_OBJDIR)/src/process/x86_64 \
    $(MUSL_OBJDIR)/src/regex \
    $(MUSL_OBJDIR)/src/sched \
    $(MUSL_OBJDIR)/src/search \
    $(MUSL_OBJDIR)/src/select \
    $(MUSL_OBJDIR)/src/setjmp/x86_64 \
    $(MUSL_OBJDIR)/src/signal \
    $(MUSL_OBJDIR)/src/signal/x86_64 \
    $(MUSL_OBJDIR)/src/stat \
    $(MUSL_OBJDIR)/src/stdio \
    $(MUSL_OBJDIR)/src/stdlib \
    $(MUSL_OBJDIR)/src/string \
    $(MUSL_OBJDIR)/src/string/x86_64 \
    $(MUSL_OBJDIR)/src/temp \
    $(MUSL_OBJDIR)/src/termios \
    $(MUSL_OBJDIR)/src/thread \
    $(MUSL_OBJDIR)/src/thread/x86_64 \
    $(MUSL_OBJDIR)/src/time \
    $(MUSL_OBJDIR)/src/unistd

MUSL_INCS =                       \
    -I$(MUSL_SUBDIR)/arch/x86_64  \
    -I$(MUSL_SUBDIR)/arch/generic \
    -I$(MUSL_SUBDIR)/src/internal \
    -I$(MUSL_SUBDIR)/include      \
    -I$(MUSL_OBJDIR)

MUSL_CRT_OBJS =       \
    $(LIBDIR)/Scrt1.o \
    $(LIBDIR)/ccrt1.o \
    $(LIBDIR)/rcrt1.o \
    $(LIBDIR)/crti.o  \
    $(LIBDIR)/crtn.o

MUSL_OBJS = \
    $(MUSL_OBJDIR)/src/mman/mlockall.o \
    $(MUSL_OBJDIR)/src/mman/mremap.o \
    $(MUSL_OBJDIR)/src/mman/mprotect.o \
    $(MUSL_OBJDIR)/src/mman/munlock.o \
    $(MUSL_OBJDIR)/src/mman/mlock.o \
    $(MUSL_OBJDIR)/src/mman/posix_madvise.o \
    $(MUSL_OBJDIR)/src/mman/mmap.o \
    $(MUSL_OBJDIR)/src/mman/munmap.o \
    $(MUSL_OBJDIR)/src/mman/madvise.o \
    $(MUSL_OBJDIR)/src/mman/msync.o \
    $(MUSL_OBJDIR)/src/mman/mincore.o \
    $(MUSL_OBJDIR)/src/mman/munlockall.o \
    $(MUSL_OBJDIR)/src/mman/shm_open.o \
    $(MUSL_OBJDIR)/src/thread/pthread_getconcurrency.o \
    $(MUSL_OBJDIR)/src/thread/pthread_cond_broadcast.o \
    $(MUSL_OBJDIR)/src/thread/thrd_create.o \
    $(MUSL_OBJDIR)/src/thread/pthread_attr_init.o \
    $(MUSL_OBJDIR)/src/thread/pthread_cond_wait.o \
    $(MUSL_OBJDIR)/src/thread/sem_trywait.o \
    $(MUSL_OBJDIR)/src/thread/sem_getvalue.o \
    $(MUSL_OBJDIR)/src/thread/thrd_exit.o \
    $(MUSL_OBJDIR)/src/thread/__set_thread_area.o \
    $(MUSL_OBJDIR)/src/thread/tss_delete.o \
    $(MUSL_OBJDIR)/src/thread/pthread_testcancel.o \
    $(MUSL_OBJDIR)/src/thread/lock_ptc.o \
    $(MUSL_OBJDIR)/src/thread/mtx_timedlock.o \
    $(MUSL_OBJDIR)/src/thread/__syscall_cp.o \
    $(MUSL_OBJDIR)/src/thread/sem_destroy.o \
    $(MUSL_OBJDIR)/src/thread/pthread_cond_timedwait.o \
    $(MUSL_OBJDIR)/src/thread/pthread_attr_setstack.o \
    $(MUSL_OBJDIR)/src/thread/sem_init.o \
    $(MUSL_OBJDIR)/src/thread/pthread_barrier_init.o \
    $(MUSL_OBJDIR)/src/thread/pthread_join.o \
    $(MUSL_OBJDIR)/src/thread/syscall_cp.o \
    $(MUSL_OBJDIR)/src/thread/cnd_destroy.o \
    $(MUSL_OBJDIR)/src/thread/pthread_barrierattr_setpshared.o \
    $(MUSL_OBJDIR)/src/thread/sem_timedwait.o \
    $(MUSL_OBJDIR)/src/thread/pthread_barrierattr_init.o \
    $(MUSL_OBJDIR)/src/thread/pthread_rwlockattr_setpshared.o \
    $(MUSL_OBJDIR)/src/thread/pthread_spin_init.o \
    $(MUSL_OBJDIR)/src/thread/pthread_attr_setscope.o \
    $(MUSL_OBJDIR)/src/thread/thrd_yield.o \
    $(MUSL_OBJDIR)/src/thread/pthread_cond_signal.o \
    $(MUSL_OBJDIR)/src/thread/pthread_condattr_setclock.o \
    $(MUSL_OBJDIR)/src/thread/mtx_lock.o \
    $(MUSL_OBJDIR)/src/thread/pthread_mutex_trylock.o \
    $(MUSL_OBJDIR)/src/thread/pthread_rwlockattr_init.o \
    $(MUSL_OBJDIR)/src/thread/pthread_rwlock_unlock.o \
    $(MUSL_OBJDIR)/src/thread/mtx_destroy.o \
    $(MUSL_OBJDIR)/src/thread/pthread_spin_destroy.o \
    $(MUSL_OBJDIR)/src/thread/__futex.o \
    $(MUSL_OBJDIR)/src/thread/pthread_setspecific.o \
    $(MUSL_OBJDIR)/src/thread/clone.o \
    $(MUSL_OBJDIR)/src/thread/pthread_setconcurrency.o \
    $(MUSL_OBJDIR)/src/thread/pthread_mutexattr_init.o \
    $(MUSL_OBJDIR)/src/thread/pthread_detach.o \
    $(MUSL_OBJDIR)/src/thread/pthread_rwlock_destroy.o \
    $(MUSL_OBJDIR)/src/thread/pthread_attr_destroy.o \
    $(MUSL_OBJDIR)/src/thread/pthread_once.o \
    $(MUSL_OBJDIR)/src/thread/pthread_rwlock_wrlock.o \
    $(MUSL_OBJDIR)/src/thread/cnd_signal.o \
    $(MUSL_OBJDIR)/src/thread/pthread_getattr_np.o \
    $(MUSL_OBJDIR)/src/thread/pthread_rwlock_timedrdlock.o \
    $(MUSL_OBJDIR)/src/thread/pthread_condattr_destroy.o \
    $(MUSL_OBJDIR)/src/thread/__wait.o \
    $(MUSL_OBJDIR)/src/thread/pthread_barrier_wait.o \
    $(MUSL_OBJDIR)/src/thread/pthread_mutex_getprioceiling.o \
    $(MUSL_OBJDIR)/src/thread/pthread_mutexattr_settype.o \
    $(MUSL_OBJDIR)/src/thread/mtx_unlock.o \
    $(MUSL_OBJDIR)/src/thread/pthread_attr_setdetachstate.o \
    $(MUSL_OBJDIR)/src/thread/pthread_mutex_consistent.o \
    $(MUSL_OBJDIR)/src/thread/pthread_barrierattr_destroy.o \
    $(MUSL_OBJDIR)/src/thread/pthread_mutex_destroy.o \
    $(MUSL_OBJDIR)/src/thread/pthread_mutexattr_setpshared.o \
    $(MUSL_OBJDIR)/src/thread/pthread_attr_setguardsize.o \
    $(MUSL_OBJDIR)/src/thread/pthread_create.o \
    $(MUSL_OBJDIR)/src/thread/pthread_mutex_lock.o \
    $(MUSL_OBJDIR)/src/thread/pthread_spin_trylock.o \
    $(MUSL_OBJDIR)/src/thread/cnd_init.o \
    $(MUSL_OBJDIR)/src/thread/cnd_broadcast.o \
    $(MUSL_OBJDIR)/src/thread/__unmapself.o \
    $(MUSL_OBJDIR)/src/thread/pthread_rwlock_rdlock.o \
    $(MUSL_OBJDIR)/src/thread/mtx_init.o \
    $(MUSL_OBJDIR)/src/thread/sem_open.o \
    $(MUSL_OBJDIR)/src/thread/sem_post.o \
    $(MUSL_OBJDIR)/src/thread/sem_unlink.o \
    $(MUSL_OBJDIR)/src/thread/pthread_equal.o \
    $(MUSL_OBJDIR)/src/thread/pthread_setschedparam.o \
    $(MUSL_OBJDIR)/src/thread/pthread_setcanceltype.o \
    $(MUSL_OBJDIR)/src/thread/pthread_sigmask.o \
    $(MUSL_OBJDIR)/src/thread/pthread_spin_unlock.o \
    $(MUSL_OBJDIR)/src/thread/pthread_cleanup_push.o \
    $(MUSL_OBJDIR)/src/thread/pthread_rwlockattr_destroy.o \
    $(MUSL_OBJDIR)/src/thread/pthread_mutex_unlock.o \
    $(MUSL_OBJDIR)/src/thread/pthread_attr_setinheritsched.o \
    $(MUSL_OBJDIR)/src/thread/pthread_cond_destroy.o \
    $(MUSL_OBJDIR)/src/thread/pthread_mutexattr_destroy.o \
    $(MUSL_OBJDIR)/src/thread/tss_set.o \
    $(MUSL_OBJDIR)/src/thread/pthread_condattr_init.o \
    $(MUSL_OBJDIR)/src/thread/pthread_rwlock_trywrlock.o \
    $(MUSL_OBJDIR)/src/thread/pthread_getschedparam.o \
    $(MUSL_OBJDIR)/src/thread/pthread_setcancelstate.o \
    $(MUSL_OBJDIR)/src/thread/thrd_join.o \
    $(MUSL_OBJDIR)/src/thread/pthread_attr_setschedpolicy.o \
    $(MUSL_OBJDIR)/src/thread/pthread_mutexattr_setrobust.o \
    $(MUSL_OBJDIR)/src/thread/tss_create.o \
    $(MUSL_OBJDIR)/src/thread/pthread_mutexattr_setprotocol.o \
    $(MUSL_OBJDIR)/src/thread/pthread_key_create.o \
    $(MUSL_OBJDIR)/src/thread/pthread_cancel.o \
    $(MUSL_OBJDIR)/src/thread/cnd_timedwait.o \
    $(MUSL_OBJDIR)/src/thread/pthread_rwlock_timedwrlock.o \
    $(MUSL_OBJDIR)/src/thread/pthread_attr_setstacksize.o \
    $(MUSL_OBJDIR)/src/thread/pthread_cond_init.o \
    $(MUSL_OBJDIR)/src/thread/__lock.o \
    $(MUSL_OBJDIR)/src/thread/pthread_attr_get.o \
    $(MUSL_OBJDIR)/src/thread/vmlock.o \
    $(MUSL_OBJDIR)/src/thread/pthread_setschedprio.o \
    $(MUSL_OBJDIR)/src/thread/pthread_mutex_setprioceiling.o \
    $(MUSL_OBJDIR)/src/thread/pthread_self.o \
    $(MUSL_OBJDIR)/src/thread/__tls_get_addr.o \
    $(MUSL_OBJDIR)/src/thread/pthread_getspecific.o \
    $(MUSL_OBJDIR)/src/thread/pthread_attr_setschedparam.o \
    $(MUSL_OBJDIR)/src/thread/pthread_kill.o \
    $(MUSL_OBJDIR)/src/thread/pthread_mutex_timedlock.o \
    $(MUSL_OBJDIR)/src/thread/synccall.o \
    $(MUSL_OBJDIR)/src/thread/__timedwait.o \
    $(MUSL_OBJDIR)/src/thread/sem_wait.o \
    $(MUSL_OBJDIR)/src/thread/call_once.o \
    $(MUSL_OBJDIR)/src/thread/pthread_getcpuclockid.o \
    $(MUSL_OBJDIR)/src/thread/pthread_rwlock_tryrdlock.o \
    $(MUSL_OBJDIR)/src/thread/pthread_condattr_setpshared.o \
    $(MUSL_OBJDIR)/src/thread/pthread_mutex_init.o \
    $(MUSL_OBJDIR)/src/thread/mtx_trylock.o \
    $(MUSL_OBJDIR)/src/thread/pthread_spin_lock.o \
    $(MUSL_OBJDIR)/src/thread/pthread_barrier_destroy.o \
    $(MUSL_OBJDIR)/src/thread/tls.o \
    $(MUSL_OBJDIR)/src/thread/pthread_atfork.o \
    $(MUSL_OBJDIR)/src/thread/pthread_rwlock_init.o \
    $(MUSL_OBJDIR)/src/thread/cnd_wait.o \
    $(MUSL_OBJDIR)/src/thread/thrd_sleep.o \
    $(MUSL_OBJDIR)/src/env/putenv.o \
    $(MUSL_OBJDIR)/src/env/__stack_chk_fail.o \
    $(MUSL_OBJDIR)/src/env/__reset_tls.o \
    $(MUSL_OBJDIR)/src/env/__libc_start_main.o \
    $(MUSL_OBJDIR)/src/env/setenv.o \
    $(MUSL_OBJDIR)/src/env/__environ.o \
    $(MUSL_OBJDIR)/src/env/unsetenv.o \
    $(MUSL_OBJDIR)/src/env/clearenv.o \
    $(MUSL_OBJDIR)/src/env/__init_tls.o \
    $(MUSL_OBJDIR)/src/env/getenv.o \
    $(MUSL_OBJDIR)/src/exit/at_quick_exit.o \
    $(MUSL_OBJDIR)/src/exit/_Exit.o \
    $(MUSL_OBJDIR)/src/exit/exit.o \
    $(MUSL_OBJDIR)/src/exit/quick_exit.o \
    $(MUSL_OBJDIR)/src/exit/atexit.o \
    $(MUSL_OBJDIR)/src/exit/assert.o \
    $(MUSL_OBJDIR)/src/exit/abort.o \
    $(MUSL_OBJDIR)/src/string/wmemcpy.o \
    $(MUSL_OBJDIR)/src/string/strlcat.o \
    $(MUSL_OBJDIR)/src/string/wcsncasecmp_l.o \
    $(MUSL_OBJDIR)/src/string/bzero.o \
    $(MUSL_OBJDIR)/src/string/strncasecmp.o \
    $(MUSL_OBJDIR)/src/string/wcspbrk.o \
    $(MUSL_OBJDIR)/src/string/wcpcpy.o \
    $(MUSL_OBJDIR)/src/string/index.o \
    $(MUSL_OBJDIR)/src/string/strdup.o \
    $(MUSL_OBJDIR)/src/string/wcsncasecmp.o \
    $(MUSL_OBJDIR)/src/string/strerror_r.o \
    $(MUSL_OBJDIR)/src/string/wcscspn.o \
    $(MUSL_OBJDIR)/src/string/memccpy.o \
    $(MUSL_OBJDIR)/src/string/wmemchr.o \
    $(MUSL_OBJDIR)/src/string/wcslen.o \
    $(MUSL_OBJDIR)/src/string/strtok_r.o \
    $(MUSL_OBJDIR)/src/string/wmemcmp.o \
    $(MUSL_OBJDIR)/src/string/strncat.o \
    $(MUSL_OBJDIR)/src/string/memcpy.o \
    $(MUSL_OBJDIR)/src/string/strchrnul.o \
    $(MUSL_OBJDIR)/src/string/strpbrk.o \
    $(MUSL_OBJDIR)/src/string/wcsspn.o \
    $(MUSL_OBJDIR)/src/string/wcsdup.o \
    $(MUSL_OBJDIR)/src/string/strcasecmp.o \
    $(MUSL_OBJDIR)/src/string/swab.o \
    $(MUSL_OBJDIR)/src/string/strnlen.o \
    $(MUSL_OBJDIR)/src/string/wcscasecmp.o \
    $(MUSL_OBJDIR)/src/string/wcsnlen.o \
    $(MUSL_OBJDIR)/src/string/memmem.o \
    $(MUSL_OBJDIR)/src/string/strcmp.o \
    $(MUSL_OBJDIR)/src/string/stpcpy.o \
    $(MUSL_OBJDIR)/src/string/wcscat.o \
    $(MUSL_OBJDIR)/src/string/strtok.o \
    $(MUSL_OBJDIR)/src/string/wcscpy.o \
    $(MUSL_OBJDIR)/src/string/wcswcs.o \
    $(MUSL_OBJDIR)/src/string/strrchr.o \
    $(MUSL_OBJDIR)/src/string/wcsstr.o \
    $(MUSL_OBJDIR)/src/string/strchr.o \
    $(MUSL_OBJDIR)/src/string/memrchr.o \
    $(MUSL_OBJDIR)/src/string/strverscmp.o \
    $(MUSL_OBJDIR)/src/string/wcsrchr.o \
    $(MUSL_OBJDIR)/src/string/strlen.o \
    $(MUSL_OBJDIR)/src/string/strspn.o \
    $(MUSL_OBJDIR)/src/string/wcscasecmp_l.o \
    $(MUSL_OBJDIR)/src/string/strcasestr.o \
    $(MUSL_OBJDIR)/src/string/strndup.o \
    $(MUSL_OBJDIR)/src/string/strsep.o \
    $(MUSL_OBJDIR)/src/string/bcopy.o \
    $(MUSL_OBJDIR)/src/string/strcpy.o \
    $(MUSL_OBJDIR)/src/string/wcschr.o \
    $(MUSL_OBJDIR)/src/string/wmemmove.o \
    $(MUSL_OBJDIR)/src/string/wcstok.o \
    $(MUSL_OBJDIR)/src/string/strncmp.o \
    $(MUSL_OBJDIR)/src/string/wcsncpy.o \
    $(MUSL_OBJDIR)/src/string/strsignal.o \
    $(MUSL_OBJDIR)/src/string/strstr.o \
    $(MUSL_OBJDIR)/src/string/wcsncat.o \
    $(MUSL_OBJDIR)/src/string/memmove.o \
    $(MUSL_OBJDIR)/src/string/memchr.o \
    $(MUSL_OBJDIR)/src/string/rindex.o \
    $(MUSL_OBJDIR)/src/string/memcmp.o \
    $(MUSL_OBJDIR)/src/string/stpncpy.o \
    $(MUSL_OBJDIR)/src/string/bcmp.o \
    $(MUSL_OBJDIR)/src/string/wmemset.o \
    $(MUSL_OBJDIR)/src/string/wcscmp.o \
    $(MUSL_OBJDIR)/src/string/wcpncpy.o \
    $(MUSL_OBJDIR)/src/string/mempcpy.o \
    $(MUSL_OBJDIR)/src/string/wcsncmp.o \
    $(MUSL_OBJDIR)/src/string/strncpy.o \
    $(MUSL_OBJDIR)/src/string/strcat.o \
    $(MUSL_OBJDIR)/src/string/memset.o \
    $(MUSL_OBJDIR)/src/string/strlcpy.o \
    $(MUSL_OBJDIR)/src/string/strcspn.o \
    $(MUSL_OBJDIR)/src/stat/chmod.o \
    $(MUSL_OBJDIR)/src/stat/umask.o \
    $(MUSL_OBJDIR)/src/stat/lchmod.o \
    $(MUSL_OBJDIR)/src/stat/fstat.o \
    $(MUSL_OBJDIR)/src/stat/stat.o \
    $(MUSL_OBJDIR)/src/stat/mknod.o \
    $(MUSL_OBJDIR)/src/stat/mkfifoat.o \
    $(MUSL_OBJDIR)/src/stat/mkfifo.o \
    $(MUSL_OBJDIR)/src/stat/__xstat.o \
    $(MUSL_OBJDIR)/src/stat/mkdirat.o \
    $(MUSL_OBJDIR)/src/stat/lstat.o \
    $(MUSL_OBJDIR)/src/stat/statvfs.o \
    $(MUSL_OBJDIR)/src/stat/futimens.o \
    $(MUSL_OBJDIR)/src/stat/mkdir.o \
    $(MUSL_OBJDIR)/src/stat/fchmodat.o \
    $(MUSL_OBJDIR)/src/stat/mknodat.o \
    $(MUSL_OBJDIR)/src/stat/utimensat.o \
    $(MUSL_OBJDIR)/src/stat/fstatat.o \
    $(MUSL_OBJDIR)/src/stat/fchmod.o \
    $(MUSL_OBJDIR)/src/stat/futimesat.o \
    $(MUSL_OBJDIR)/src/fcntl/openat.o \
    $(MUSL_OBJDIR)/src/fcntl/posix_fallocate.o \
    $(MUSL_OBJDIR)/src/fcntl/posix_fadvise.o \
    $(MUSL_OBJDIR)/src/fcntl/fcntl.o \
    $(MUSL_OBJDIR)/src/fcntl/open.o \
    $(MUSL_OBJDIR)/src/fcntl/creat.o \
    $(MUSL_OBJDIR)/src/sched/sched_get_priority_max.o \
    $(MUSL_OBJDIR)/src/sched/sched_yield.o \
    $(MUSL_OBJDIR)/src/sched/sched_setscheduler.o \
    $(MUSL_OBJDIR)/src/sched/sched_setparam.o \
    $(MUSL_OBJDIR)/src/sched/sched_getparam.o \
    $(MUSL_OBJDIR)/src/sched/sched_getscheduler.o \
    $(MUSL_OBJDIR)/src/sched/affinity.o \
    $(MUSL_OBJDIR)/src/sched/sched_rr_get_interval.o \
    $(MUSL_OBJDIR)/src/sched/sched_cpucount.o \
    $(MUSL_OBJDIR)/src/ipc/shmget.o \
    $(MUSL_OBJDIR)/src/ipc/shmctl.o \
    $(MUSL_OBJDIR)/src/ipc/shmat.o \
    $(MUSL_OBJDIR)/src/ipc/semop.o \
    $(MUSL_OBJDIR)/src/ipc/msgsnd.o \
    $(MUSL_OBJDIR)/src/ipc/shmdt.o \
    $(MUSL_OBJDIR)/src/ipc/semget.o \
    $(MUSL_OBJDIR)/src/ipc/semtimedop.o \
    $(MUSL_OBJDIR)/src/ipc/semctl.o \
    $(MUSL_OBJDIR)/src/ipc/msgrcv.o \
    $(MUSL_OBJDIR)/src/ipc/msgget.o \
    $(MUSL_OBJDIR)/src/ipc/msgctl.o \
    $(MUSL_OBJDIR)/src/ipc/ftok.o \
    $(MUSL_OBJDIR)/src/select/poll.o \
    $(MUSL_OBJDIR)/src/select/pselect.o \
    $(MUSL_OBJDIR)/src/select/select.o \
    $(MUSL_OBJDIR)/src/search/insque.o \
    $(MUSL_OBJDIR)/src/search/tdestroy.o \
    $(MUSL_OBJDIR)/src/search/lsearch.o \
    $(MUSL_OBJDIR)/src/search/hsearch.o \
    $(MUSL_OBJDIR)/src/search/tsearch_avl.o \
    $(MUSL_OBJDIR)/src/malloc/lite_malloc.o \
    $(MUSL_OBJDIR)/src/malloc/malloc.o \
    $(MUSL_OBJDIR)/src/malloc/expand_heap.o \
    $(MUSL_OBJDIR)/src/malloc/__brk.o \
    $(MUSL_OBJDIR)/src/malloc/malloc_usable_size.o \
    $(MUSL_OBJDIR)/src/malloc/calloc.o \
    $(MUSL_OBJDIR)/src/malloc/posix_memalign.o \
    $(MUSL_OBJDIR)/src/malloc/memalign.o \
    $(MUSL_OBJDIR)/src/malloc/aligned_alloc.o \
    $(MUSL_OBJDIR)/src/termios/tcflow.o \
    $(MUSL_OBJDIR)/src/termios/cfgetospeed.o \
    $(MUSL_OBJDIR)/src/termios/tcgetattr.o \
    $(MUSL_OBJDIR)/src/termios/tcsetattr.o \
    $(MUSL_OBJDIR)/src/termios/tcgetsid.o \
    $(MUSL_OBJDIR)/src/termios/cfsetospeed.o \
    $(MUSL_OBJDIR)/src/termios/tcdrain.o \
    $(MUSL_OBJDIR)/src/termios/tcsendbreak.o \
    $(MUSL_OBJDIR)/src/termios/cfmakeraw.o \
    $(MUSL_OBJDIR)/src/termios/tcflush.o \
    $(MUSL_OBJDIR)/src/complex/cimag.o \
    $(MUSL_OBJDIR)/src/complex/casin.o \
    $(MUSL_OBJDIR)/src/complex/ccos.o \
    $(MUSL_OBJDIR)/src/complex/cacoshf.o \
    $(MUSL_OBJDIR)/src/complex/conj.o \
    $(MUSL_OBJDIR)/src/complex/cprojf.o \
    $(MUSL_OBJDIR)/src/complex/csinf.o \
    $(MUSL_OBJDIR)/src/complex/clogl.o \
    $(MUSL_OBJDIR)/src/complex/csinhl.o \
    $(MUSL_OBJDIR)/src/complex/conjl.o \
    $(MUSL_OBJDIR)/src/complex/cargf.o \
    $(MUSL_OBJDIR)/src/complex/catanhf.o \
    $(MUSL_OBJDIR)/src/complex/csqrt.o \
    $(MUSL_OBJDIR)/src/complex/cacos.o \
    $(MUSL_OBJDIR)/src/complex/cpow.o \
    $(MUSL_OBJDIR)/src/complex/catan.o \
    $(MUSL_OBJDIR)/src/complex/clogf.o \
    $(MUSL_OBJDIR)/src/complex/ctanhf.o \
    $(MUSL_OBJDIR)/src/complex/catanh.o \
    $(MUSL_OBJDIR)/src/complex/csinhf.o \
    $(MUSL_OBJDIR)/src/complex/ccosf.o \
    $(MUSL_OBJDIR)/src/complex/casinhf.o \
    $(MUSL_OBJDIR)/src/complex/cimagl.o \
    $(MUSL_OBJDIR)/src/complex/csqrtl.o \
    $(MUSL_OBJDIR)/src/complex/ccosl.o \
    $(MUSL_OBJDIR)/src/complex/ccoshf.o \
    $(MUSL_OBJDIR)/src/complex/casinhl.o \
    $(MUSL_OBJDIR)/src/complex/cacosf.o \
    $(MUSL_OBJDIR)/src/complex/cacosh.o \
    $(MUSL_OBJDIR)/src/complex/csinl.o \
    $(MUSL_OBJDIR)/src/complex/cexpf.o \
    $(MUSL_OBJDIR)/src/complex/casinl.o \
    $(MUSL_OBJDIR)/src/complex/cabsf.o \
    $(MUSL_OBJDIR)/src/complex/catanhl.o \
    $(MUSL_OBJDIR)/src/complex/crealf.o \
    $(MUSL_OBJDIR)/src/complex/ccosh.o \
    $(MUSL_OBJDIR)/src/complex/ccoshl.o \
    $(MUSL_OBJDIR)/src/complex/cproj.o \
    $(MUSL_OBJDIR)/src/complex/cacoshl.o \
    $(MUSL_OBJDIR)/src/complex/csqrtf.o \
    $(MUSL_OBJDIR)/src/complex/cabs.o \
    $(MUSL_OBJDIR)/src/complex/creal.o \
    $(MUSL_OBJDIR)/src/complex/cpowl.o \
    $(MUSL_OBJDIR)/src/complex/conjf.o \
    $(MUSL_OBJDIR)/src/complex/ctanf.o \
    $(MUSL_OBJDIR)/src/complex/ctanl.o \
    $(MUSL_OBJDIR)/src/complex/ctanhl.o \
    $(MUSL_OBJDIR)/src/complex/catanf.o \
    $(MUSL_OBJDIR)/src/complex/__cexpf.o \
    $(MUSL_OBJDIR)/src/complex/casinf.o \
    $(MUSL_OBJDIR)/src/complex/ctan.o \
    $(MUSL_OBJDIR)/src/complex/ctanh.o \
    $(MUSL_OBJDIR)/src/complex/cabsl.o \
    $(MUSL_OBJDIR)/src/complex/csin.o \
    $(MUSL_OBJDIR)/src/complex/cprojl.o \
    $(MUSL_OBJDIR)/src/complex/carg.o \
    $(MUSL_OBJDIR)/src/complex/__cexp.o \
    $(MUSL_OBJDIR)/src/complex/clog.o \
    $(MUSL_OBJDIR)/src/complex/cargl.o \
    $(MUSL_OBJDIR)/src/complex/catanl.o \
    $(MUSL_OBJDIR)/src/complex/cpowf.o \
    $(MUSL_OBJDIR)/src/complex/casinh.o \
    $(MUSL_OBJDIR)/src/complex/cexp.o \
    $(MUSL_OBJDIR)/src/complex/cexpl.o \
    $(MUSL_OBJDIR)/src/complex/cacosl.o \
    $(MUSL_OBJDIR)/src/complex/csinh.o \
    $(MUSL_OBJDIR)/src/complex/creall.o \
    $(MUSL_OBJDIR)/src/complex/cimagf.o \
    $(MUSL_OBJDIR)/src/multibyte/mblen.o \
    $(MUSL_OBJDIR)/src/multibyte/wcstombs.o \
    $(MUSL_OBJDIR)/src/multibyte/c32rtomb.o \
    $(MUSL_OBJDIR)/src/multibyte/btowc.o \
    $(MUSL_OBJDIR)/src/multibyte/mbtowc.o \
    $(MUSL_OBJDIR)/src/multibyte/mbsrtowcs.o \
    $(MUSL_OBJDIR)/src/multibyte/mbrlen.o \
    $(MUSL_OBJDIR)/src/multibyte/mbsnrtowcs.o \
    $(MUSL_OBJDIR)/src/multibyte/mbsinit.o \
    $(MUSL_OBJDIR)/src/multibyte/c16rtomb.o \
    $(MUSL_OBJDIR)/src/multibyte/wcrtomb.o \
    $(MUSL_OBJDIR)/src/multibyte/mbrtowc.o \
    $(MUSL_OBJDIR)/src/multibyte/mbrtoc32.o \
    $(MUSL_OBJDIR)/src/multibyte/mbrtoc16.o \
    $(MUSL_OBJDIR)/src/multibyte/mbstowcs.o \
    $(MUSL_OBJDIR)/src/multibyte/internal.o \
    $(MUSL_OBJDIR)/src/multibyte/wcsrtombs.o \
    $(MUSL_OBJDIR)/src/multibyte/wctomb.o \
    $(MUSL_OBJDIR)/src/multibyte/wcsnrtombs.o \
    $(MUSL_OBJDIR)/src/multibyte/wctob.o \
    $(MUSL_OBJDIR)/src/linux/quotactl.o \
    $(MUSL_OBJDIR)/src/linux/vmsplice.o \
    $(MUSL_OBJDIR)/src/linux/module.o \
    $(MUSL_OBJDIR)/src/linux/reboot.o \
    $(MUSL_OBJDIR)/src/linux/readahead.o \
    $(MUSL_OBJDIR)/src/linux/sendfile.o \
    $(MUSL_OBJDIR)/src/linux/sbrk.o \
    $(MUSL_OBJDIR)/src/linux/adjtime.o \
    $(MUSL_OBJDIR)/src/linux/adjtimex.o \
    $(MUSL_OBJDIR)/src/linux/vhangup.o \
    $(MUSL_OBJDIR)/src/linux/sync_file_range.o \
    $(MUSL_OBJDIR)/src/linux/clone.o \
    $(MUSL_OBJDIR)/src/linux/sethostname.o \
    $(MUSL_OBJDIR)/src/linux/cache.o \
    $(MUSL_OBJDIR)/src/linux/sysinfo.o \
    $(MUSL_OBJDIR)/src/linux/ppoll.o \
    $(MUSL_OBJDIR)/src/linux/arch_prctl.o \
    $(MUSL_OBJDIR)/src/linux/swap.o \
    $(MUSL_OBJDIR)/src/linux/ptrace.o \
    $(MUSL_OBJDIR)/src/linux/flock.o \
    $(MUSL_OBJDIR)/src/linux/cap.o \
    $(MUSL_OBJDIR)/src/linux/unshare.o \
    $(MUSL_OBJDIR)/src/linux/fallocate.o \
    $(MUSL_OBJDIR)/src/linux/setfsuid.o \
    $(MUSL_OBJDIR)/src/linux/inotify.o \
    $(MUSL_OBJDIR)/src/linux/setgroups.o \
    $(MUSL_OBJDIR)/src/linux/klogctl.o \
    $(MUSL_OBJDIR)/src/linux/setfsgid.o \
    $(MUSL_OBJDIR)/src/linux/prlimit.o \
    $(MUSL_OBJDIR)/src/linux/remap_file_pages.o \
    $(MUSL_OBJDIR)/src/linux/pivot_root.o \
    $(MUSL_OBJDIR)/src/linux/iopl.o \
    $(MUSL_OBJDIR)/src/linux/eventfd.o \
    $(MUSL_OBJDIR)/src/linux/process_vm.o \
    $(MUSL_OBJDIR)/src/linux/syncfs.o \
    $(MUSL_OBJDIR)/src/linux/prctl.o \
    $(MUSL_OBJDIR)/src/linux/epoll.o \
    $(MUSL_OBJDIR)/src/linux/ioperm.o \
    $(MUSL_OBJDIR)/src/linux/clock_adjtime.o \
    $(MUSL_OBJDIR)/src/linux/tee.o \
    $(MUSL_OBJDIR)/src/linux/utimes.o \
    $(MUSL_OBJDIR)/src/linux/mount.o \
    $(MUSL_OBJDIR)/src/linux/brk.o \
    $(MUSL_OBJDIR)/src/linux/xattr.o \
    $(MUSL_OBJDIR)/src/linux/wait4.o \
    $(MUSL_OBJDIR)/src/linux/chroot.o \
    $(MUSL_OBJDIR)/src/linux/timerfd.o \
    $(MUSL_OBJDIR)/src/linux/setns.o \
    $(MUSL_OBJDIR)/src/linux/fanotify.o \
    $(MUSL_OBJDIR)/src/linux/settimeofday.o \
    $(MUSL_OBJDIR)/src/linux/stime.o \
    $(MUSL_OBJDIR)/src/linux/personality.o \
    $(MUSL_OBJDIR)/src/linux/signalfd.o \
    $(MUSL_OBJDIR)/src/linux/wait3.o \
    $(MUSL_OBJDIR)/src/linux/splice.o \
    $(MUSL_OBJDIR)/src/internal/syscall_ret.o \
    $(MUSL_OBJDIR)/src/internal/version.o \
    $(MUSL_OBJDIR)/src/internal/vdso.o \
    $(MUSL_OBJDIR)/src/internal/intscan.o \
    $(MUSL_OBJDIR)/src/internal/libc.o \
    $(MUSL_OBJDIR)/src/internal/floatscan.o \
    $(MUSL_OBJDIR)/src/internal/procfdname.o \
    $(MUSL_OBJDIR)/src/internal/shgetc.o \
    $(MUSL_OBJDIR)/src/internal/syscall.o \
    $(MUSL_OBJDIR)/src/locale/locale_map.o \
    $(MUSL_OBJDIR)/src/locale/__lctrans.o \
    $(MUSL_OBJDIR)/src/locale/wcsxfrm.o \
    $(MUSL_OBJDIR)/src/locale/textdomain.o \
    $(MUSL_OBJDIR)/src/locale/localeconv.o \
    $(MUSL_OBJDIR)/src/locale/pleval.o \
    $(MUSL_OBJDIR)/src/locale/catclose.o \
    $(MUSL_OBJDIR)/src/locale/c_locale.o \
    $(MUSL_OBJDIR)/src/locale/uselocale.o \
    $(MUSL_OBJDIR)/src/locale/newlocale.o \
    $(MUSL_OBJDIR)/src/locale/strcoll.o \
    $(MUSL_OBJDIR)/src/locale/strxfrm.o \
    $(MUSL_OBJDIR)/src/locale/langinfo.o \
    $(MUSL_OBJDIR)/src/locale/dcngettext.o \
    $(MUSL_OBJDIR)/src/locale/bind_textdomain_codeset.o \
    $(MUSL_OBJDIR)/src/locale/catopen.o \
    $(MUSL_OBJDIR)/src/locale/iconv.o \
    $(MUSL_OBJDIR)/src/locale/freelocale.o \
    $(MUSL_OBJDIR)/src/locale/strfmon.o \
    $(MUSL_OBJDIR)/src/locale/wcscoll.o \
    $(MUSL_OBJDIR)/src/locale/catgets.o \
    $(MUSL_OBJDIR)/src/locale/setlocale.o \
    $(MUSL_OBJDIR)/src/locale/duplocale.o \
    $(MUSL_OBJDIR)/src/locale/__mo_lookup.o \
    $(MUSL_OBJDIR)/src/network/if_nametoindex.o \
    $(MUSL_OBJDIR)/src/network/getaddrinfo.o \
    $(MUSL_OBJDIR)/src/network/herror.o \
    $(MUSL_OBJDIR)/src/network/inet_ntop.o \
    $(MUSL_OBJDIR)/src/network/res_query.o \
    $(MUSL_OBJDIR)/src/network/getsockname.o \
    $(MUSL_OBJDIR)/src/network/gethostbyname2.o \
    $(MUSL_OBJDIR)/src/network/getnameinfo.o \
    $(MUSL_OBJDIR)/src/network/recvmmsg.o \
    $(MUSL_OBJDIR)/src/network/getpeername.o \
    $(MUSL_OBJDIR)/src/network/serv.o \
    $(MUSL_OBJDIR)/src/network/lookup_name.o \
    $(MUSL_OBJDIR)/src/network/ns_parse.o \
    $(MUSL_OBJDIR)/src/network/sendmsg.o \
    $(MUSL_OBJDIR)/src/network/accept.o \
    $(MUSL_OBJDIR)/src/network/htons.o \
    $(MUSL_OBJDIR)/src/network/inet_aton.o \
    $(MUSL_OBJDIR)/src/network/getservbyport_r.o \
    $(MUSL_OBJDIR)/src/network/res_send.o \
    $(MUSL_OBJDIR)/src/network/bind.o \
    $(MUSL_OBJDIR)/src/network/res_init.o \
    $(MUSL_OBJDIR)/src/network/inet_ntoa.o \
    $(MUSL_OBJDIR)/src/network/sockatmark.o \
    $(MUSL_OBJDIR)/src/network/h_errno.o \
    $(MUSL_OBJDIR)/src/network/recvmsg.o \
    $(MUSL_OBJDIR)/src/network/recvfrom.o \
    $(MUSL_OBJDIR)/src/network/in6addr_any.o \
    $(MUSL_OBJDIR)/src/network/setsockopt.o \
    $(MUSL_OBJDIR)/src/network/dns_parse.o \
    $(MUSL_OBJDIR)/src/network/getifaddrs.o \
    $(MUSL_OBJDIR)/src/network/sendmmsg.o \
    $(MUSL_OBJDIR)/src/network/gethostbyaddr_r.o \
    $(MUSL_OBJDIR)/src/network/ent.o \
    $(MUSL_OBJDIR)/src/network/res_msend.o \
    $(MUSL_OBJDIR)/src/network/res_mkquery.o \
    $(MUSL_OBJDIR)/src/network/gethostbyname_r.o \
    $(MUSL_OBJDIR)/src/network/ntohs.o \
    $(MUSL_OBJDIR)/src/network/accept4.o \
    $(MUSL_OBJDIR)/src/network/hstrerror.o \
    $(MUSL_OBJDIR)/src/network/proto.o \
    $(MUSL_OBJDIR)/src/network/res_querydomain.o \
    $(MUSL_OBJDIR)/src/network/inet_pton.o \
    $(MUSL_OBJDIR)/src/network/resolvconf.o \
    $(MUSL_OBJDIR)/src/network/gethostbyname.o \
    $(MUSL_OBJDIR)/src/network/dn_expand.o \
    $(MUSL_OBJDIR)/src/network/freeaddrinfo.o \
    $(MUSL_OBJDIR)/src/network/sendto.o \
    $(MUSL_OBJDIR)/src/network/getservbyname.o \
    $(MUSL_OBJDIR)/src/network/gethostbyaddr.o \
    $(MUSL_OBJDIR)/src/network/netlink.o \
    $(MUSL_OBJDIR)/src/network/lookup_ipliteral.o \
    $(MUSL_OBJDIR)/src/network/recv.o \
    $(MUSL_OBJDIR)/src/network/socketpair.o \
    $(MUSL_OBJDIR)/src/network/lookup_serv.o \
    $(MUSL_OBJDIR)/src/network/send.o \
    $(MUSL_OBJDIR)/src/network/ntohl.o \
    $(MUSL_OBJDIR)/src/network/getservbyport.o \
    $(MUSL_OBJDIR)/src/network/netname.o \
    $(MUSL_OBJDIR)/src/network/connect.o \
    $(MUSL_OBJDIR)/src/network/socket.o \
    $(MUSL_OBJDIR)/src/network/ether.o \
    $(MUSL_OBJDIR)/src/network/getsockopt.o \
    $(MUSL_OBJDIR)/src/network/if_indextoname.o \
    $(MUSL_OBJDIR)/src/network/listen.o \
    $(MUSL_OBJDIR)/src/network/dn_comp.o \
    $(MUSL_OBJDIR)/src/network/gethostbyname2_r.o \
    $(MUSL_OBJDIR)/src/network/dn_skipname.o \
    $(MUSL_OBJDIR)/src/network/if_freenameindex.o \
    $(MUSL_OBJDIR)/src/network/htonl.o \
    $(MUSL_OBJDIR)/src/network/shutdown.o \
    $(MUSL_OBJDIR)/src/network/inet_addr.o \
    $(MUSL_OBJDIR)/src/network/gai_strerror.o \
    $(MUSL_OBJDIR)/src/network/res_state.o \
    $(MUSL_OBJDIR)/src/network/in6addr_loopback.o \
    $(MUSL_OBJDIR)/src/network/if_nameindex.o \
    $(MUSL_OBJDIR)/src/network/getservbyname_r.o \
    $(MUSL_OBJDIR)/src/network/inet_legacy.o \
    $(MUSL_OBJDIR)/src/conf/legacy.o \
    $(MUSL_OBJDIR)/src/conf/confstr.o \
    $(MUSL_OBJDIR)/src/conf/fpathconf.o \
    $(MUSL_OBJDIR)/src/conf/pathconf.o \
    $(MUSL_OBJDIR)/src/conf/sysconf.o \
    $(MUSL_OBJDIR)/src/stdio/vscanf.o \
    $(MUSL_OBJDIR)/src/stdio/vfwscanf.o \
    $(MUSL_OBJDIR)/src/stdio/tmpnam.o \
    $(MUSL_OBJDIR)/src/stdio/freopen.o \
    $(MUSL_OBJDIR)/src/stdio/ftrylockfile.o \
    $(MUSL_OBJDIR)/src/stdio/vwscanf.o \
    $(MUSL_OBJDIR)/src/stdio/fileno.o \
    $(MUSL_OBJDIR)/src/stdio/__stdio_close.o \
    $(MUSL_OBJDIR)/src/stdio/__fopen_rb_ca.o \
    $(MUSL_OBJDIR)/src/stdio/wscanf.o \
    $(MUSL_OBJDIR)/src/stdio/vdprintf.o \
    $(MUSL_OBJDIR)/src/stdio/fgetwc.o \
    $(MUSL_OBJDIR)/src/stdio/open_wmemstream.o \
    $(MUSL_OBJDIR)/src/stdio/fprintf.o \
    $(MUSL_OBJDIR)/src/stdio/vfprintf.o \
    $(MUSL_OBJDIR)/src/stdio/putchar.o \
    $(MUSL_OBJDIR)/src/stdio/vswscanf.o \
    $(MUSL_OBJDIR)/src/stdio/stdin.o \
    $(MUSL_OBJDIR)/src/stdio/fputc.o \
    $(MUSL_OBJDIR)/src/stdio/vfscanf.o \
    $(MUSL_OBJDIR)/src/stdio/sscanf.o \
    $(MUSL_OBJDIR)/src/stdio/__overflow.o \
    $(MUSL_OBJDIR)/src/stdio/dprintf.o \
    $(MUSL_OBJDIR)/src/stdio/putc.o \
    $(MUSL_OBJDIR)/src/stdio/tempnam.o \
    $(MUSL_OBJDIR)/src/stdio/putc_unlocked.o \
    $(MUSL_OBJDIR)/src/stdio/fgetln.o \
    $(MUSL_OBJDIR)/src/stdio/__towrite.o \
    $(MUSL_OBJDIR)/src/stdio/wprintf.o \
    $(MUSL_OBJDIR)/src/stdio/fgets.o \
    $(MUSL_OBJDIR)/src/stdio/putchar_unlocked.o \
    $(MUSL_OBJDIR)/src/stdio/pclose.o \
    $(MUSL_OBJDIR)/src/stdio/ftell.o \
    $(MUSL_OBJDIR)/src/stdio/funlockfile.o \
    $(MUSL_OBJDIR)/src/stdio/__string_read.o \
    $(MUSL_OBJDIR)/src/stdio/__fmodeflags.o \
    $(MUSL_OBJDIR)/src/stdio/__stdio_read.o \
    $(MUSL_OBJDIR)/src/stdio/open_memstream.o \
    $(MUSL_OBJDIR)/src/stdio/setbuffer.o \
    $(MUSL_OBJDIR)/src/stdio/flockfile.o \
    $(MUSL_OBJDIR)/src/stdio/fgetpos.o \
    $(MUSL_OBJDIR)/src/stdio/fwide.o \
    $(MUSL_OBJDIR)/src/stdio/ferror.o \
    $(MUSL_OBJDIR)/src/stdio/__stdio_write.o \
    $(MUSL_OBJDIR)/src/stdio/asprintf.o \
    $(MUSL_OBJDIR)/src/stdio/getline.o \
    $(MUSL_OBJDIR)/src/stdio/fgetc.o \
    $(MUSL_OBJDIR)/src/stdio/rename.o \
    $(MUSL_OBJDIR)/src/stdio/__fclose_ca.o \
    $(MUSL_OBJDIR)/src/stdio/vsprintf.o \
    $(MUSL_OBJDIR)/src/stdio/snprintf.o \
    $(MUSL_OBJDIR)/src/stdio/feof.o \
    $(MUSL_OBJDIR)/src/stdio/swscanf.o \
    $(MUSL_OBJDIR)/src/stdio/fscanf.o \
    $(MUSL_OBJDIR)/src/stdio/fputwc.o \
    $(MUSL_OBJDIR)/src/stdio/gets.o \
    $(MUSL_OBJDIR)/src/stdio/vswprintf.o \
    $(MUSL_OBJDIR)/src/stdio/__lockfile.o \
    $(MUSL_OBJDIR)/src/stdio/ungetwc.o \
    $(MUSL_OBJDIR)/src/stdio/fwrite.o \
    $(MUSL_OBJDIR)/src/stdio/ext.o \
    $(MUSL_OBJDIR)/src/stdio/putwchar.o \
    $(MUSL_OBJDIR)/src/stdio/setlinebuf.o \
    $(MUSL_OBJDIR)/src/stdio/fopen.o \
    $(MUSL_OBJDIR)/src/stdio/printf.o \
    $(MUSL_OBJDIR)/src/stdio/popen.o \
    $(MUSL_OBJDIR)/src/stdio/fwprintf.o \
    $(MUSL_OBJDIR)/src/stdio/getdelim.o \
    $(MUSL_OBJDIR)/src/stdio/fputs.o \
    $(MUSL_OBJDIR)/src/stdio/fseek.o \
    $(MUSL_OBJDIR)/src/stdio/getw.o \
    $(MUSL_OBJDIR)/src/stdio/stdout.o \
    $(MUSL_OBJDIR)/src/stdio/fmemopen.o \
    $(MUSL_OBJDIR)/src/stdio/tmpfile.o \
    $(MUSL_OBJDIR)/src/stdio/__stdio_seek.o \
    $(MUSL_OBJDIR)/src/stdio/vsscanf.o \
    $(MUSL_OBJDIR)/src/stdio/vfwprintf.o \
    $(MUSL_OBJDIR)/src/stdio/swprintf.o \
    $(MUSL_OBJDIR)/src/stdio/fread.o \
    $(MUSL_OBJDIR)/src/stdio/fgetws.o \
    $(MUSL_OBJDIR)/src/stdio/__fdopen.o \
    $(MUSL_OBJDIR)/src/stdio/rewind.o \
    $(MUSL_OBJDIR)/src/stdio/getchar_unlocked.o \
    $(MUSL_OBJDIR)/src/stdio/puts.o \
    $(MUSL_OBJDIR)/src/stdio/getc.o \
    $(MUSL_OBJDIR)/src/stdio/getc_unlocked.o \
    $(MUSL_OBJDIR)/src/stdio/ungetc.o \
    $(MUSL_OBJDIR)/src/stdio/__stdio_exit.o \
    $(MUSL_OBJDIR)/src/stdio/fwscanf.o \
    $(MUSL_OBJDIR)/src/stdio/clearerr.o \
    $(MUSL_OBJDIR)/src/stdio/ext2.o \
    $(MUSL_OBJDIR)/src/stdio/vasprintf.o \
    $(MUSL_OBJDIR)/src/stdio/getwchar.o \
    $(MUSL_OBJDIR)/src/stdio/__uflow.o \
    $(MUSL_OBJDIR)/src/stdio/stderr.o \
    $(MUSL_OBJDIR)/src/stdio/fsetpos.o \
    $(MUSL_OBJDIR)/src/stdio/ofl_add.o \
    $(MUSL_OBJDIR)/src/stdio/vsnprintf.o \
    $(MUSL_OBJDIR)/src/stdio/perror.o \
    $(MUSL_OBJDIR)/src/stdio/scanf.o \
    $(MUSL_OBJDIR)/src/stdio/fputws.o \
    $(MUSL_OBJDIR)/src/stdio/vwprintf.o \
    $(MUSL_OBJDIR)/src/stdio/__stdout_write.o \
    $(MUSL_OBJDIR)/src/stdio/__toread.o \
    $(MUSL_OBJDIR)/src/stdio/ofl.o \
    $(MUSL_OBJDIR)/src/stdio/putw.o \
    $(MUSL_OBJDIR)/src/stdio/remove.o \
    $(MUSL_OBJDIR)/src/stdio/sprintf.o \
    $(MUSL_OBJDIR)/src/stdio/getwc.o \
    $(MUSL_OBJDIR)/src/stdio/setbuf.o \
    $(MUSL_OBJDIR)/src/stdio/fflush.o \
    $(MUSL_OBJDIR)/src/stdio/getchar.o \
    $(MUSL_OBJDIR)/src/stdio/putwc.o \
    $(MUSL_OBJDIR)/src/stdio/fclose.o \
    $(MUSL_OBJDIR)/src/stdio/vprintf.o \
    $(MUSL_OBJDIR)/src/stdio/setvbuf.o \
    $(MUSL_OBJDIR)/src/math/atanh.o \
    $(MUSL_OBJDIR)/src/math/lgamma_r.o \
    $(MUSL_OBJDIR)/src/math/asinf.o \
    $(MUSL_OBJDIR)/src/math/__rem_pio2_large.o \
    $(MUSL_OBJDIR)/src/math/llrint.o \
    $(MUSL_OBJDIR)/src/math/truncl.o \
    $(MUSL_OBJDIR)/src/math/tanf.o \
    $(MUSL_OBJDIR)/src/math/j0f.o \
    $(MUSL_OBJDIR)/src/math/sincosf.o \
    $(MUSL_OBJDIR)/src/math/tgamma.o \
    $(MUSL_OBJDIR)/src/math/expf.o \
    $(MUSL_OBJDIR)/src/math/__tanl.o \
    $(MUSL_OBJDIR)/src/math/nan.o \
    $(MUSL_OBJDIR)/src/math/tanhf.o \
    $(MUSL_OBJDIR)/src/math/__expo2.o \
    $(MUSL_OBJDIR)/src/math/nearbyintf.o \
    $(MUSL_OBJDIR)/src/math/fabs.o \
    $(MUSL_OBJDIR)/src/math/modfl.o \
    $(MUSL_OBJDIR)/src/math/erfl.o \
    $(MUSL_OBJDIR)/src/math/sinhl.o \
    $(MUSL_OBJDIR)/src/math/asinhl.o \
    $(MUSL_OBJDIR)/src/math/sinf.o \
    $(MUSL_OBJDIR)/src/math/fmod.o \
    $(MUSL_OBJDIR)/src/math/ilogb.o \
    $(MUSL_OBJDIR)/src/math/acos.o \
    $(MUSL_OBJDIR)/src/math/__rem_pio2.o \
    $(MUSL_OBJDIR)/src/math/__cos.o \
    $(MUSL_OBJDIR)/src/math/atan2f.o \
    $(MUSL_OBJDIR)/src/math/cbrtf.o \
    $(MUSL_OBJDIR)/src/math/acosl.o \
    $(MUSL_OBJDIR)/src/math/sinhf.o \
    $(MUSL_OBJDIR)/src/math/remainderf.o \
    $(MUSL_OBJDIR)/src/math/fdimf.o \
    $(MUSL_OBJDIR)/src/math/frexpf.o \
    $(MUSL_OBJDIR)/src/math/__sin.o \
    $(MUSL_OBJDIR)/src/math/exp2l.o \
    $(MUSL_OBJDIR)/src/math/tanh.o \
    $(MUSL_OBJDIR)/src/math/nexttowardf.o \
    $(MUSL_OBJDIR)/src/math/log1p.o \
    $(MUSL_OBJDIR)/src/math/hypotf.o \
    $(MUSL_OBJDIR)/src/math/log10l.o \
    $(MUSL_OBJDIR)/src/math/cos.o \
    $(MUSL_OBJDIR)/src/math/powl.o \
    $(MUSL_OBJDIR)/src/math/nanf.o \
    $(MUSL_OBJDIR)/src/math/lroundf.o \
    $(MUSL_OBJDIR)/src/math/asin.o \
    $(MUSL_OBJDIR)/src/math/asinh.o \
    $(MUSL_OBJDIR)/src/math/expm1l.o \
    $(MUSL_OBJDIR)/src/math/lgammal.o \
    $(MUSL_OBJDIR)/src/math/copysign.o \
    $(MUSL_OBJDIR)/src/math/scalbnf.o \
    $(MUSL_OBJDIR)/src/math/exp2f.o \
    $(MUSL_OBJDIR)/src/math/exp10f.o \
    $(MUSL_OBJDIR)/src/math/fabsl.o \
    $(MUSL_OBJDIR)/src/math/fma.o \
    $(MUSL_OBJDIR)/src/math/finite.o \
    $(MUSL_OBJDIR)/src/math/signgam.o \
    $(MUSL_OBJDIR)/src/math/__signbitf.o \
    $(MUSL_OBJDIR)/src/math/ceill.o \
    $(MUSL_OBJDIR)/src/math/nanl.o \
    $(MUSL_OBJDIR)/src/math/roundf.o \
    $(MUSL_OBJDIR)/src/math/scalblnl.o \
    $(MUSL_OBJDIR)/src/math/hypotl.o \
    $(MUSL_OBJDIR)/src/math/__fpclassifyl.o \
    $(MUSL_OBJDIR)/src/math/copysignl.o \
    $(MUSL_OBJDIR)/src/math/frexp.o \
    $(MUSL_OBJDIR)/src/math/atanf.o \
    $(MUSL_OBJDIR)/src/math/powf.o \
    $(MUSL_OBJDIR)/src/math/ldexpl.o \
    $(MUSL_OBJDIR)/src/math/atan2.o \
    $(MUSL_OBJDIR)/src/math/fmodl.o \
    $(MUSL_OBJDIR)/src/math/__tan.o \
    $(MUSL_OBJDIR)/src/math/erf.o \
    $(MUSL_OBJDIR)/src/math/nexttoward.o \
    $(MUSL_OBJDIR)/src/math/exp.o \
    $(MUSL_OBJDIR)/src/math/nexttowardl.o \
    $(MUSL_OBJDIR)/src/math/logbl.o \
    $(MUSL_OBJDIR)/src/math/exp10l.o \
    $(MUSL_OBJDIR)/src/math/fmaf.o \
    $(MUSL_OBJDIR)/src/math/llrintf.o \
    $(MUSL_OBJDIR)/src/math/log2.o \
    $(MUSL_OBJDIR)/src/math/sinh.o \
    $(MUSL_OBJDIR)/src/math/atanhl.o \
    $(MUSL_OBJDIR)/src/math/jn.o \
    $(MUSL_OBJDIR)/src/math/floorf.o \
    $(MUSL_OBJDIR)/src/math/sqrtl.o \
    $(MUSL_OBJDIR)/src/math/roundl.o \
    $(MUSL_OBJDIR)/src/math/cbrtl.o \
    $(MUSL_OBJDIR)/src/math/__fpclassifyf.o \
    $(MUSL_OBJDIR)/src/math/__signbit.o \
    $(MUSL_OBJDIR)/src/math/acoshf.o \
    $(MUSL_OBJDIR)/src/math/acosh.o \
    $(MUSL_OBJDIR)/src/math/lgamma.o \
    $(MUSL_OBJDIR)/src/math/fmal.o \
    $(MUSL_OBJDIR)/src/math/log10.o \
    $(MUSL_OBJDIR)/src/math/sqrt.o \
    $(MUSL_OBJDIR)/src/math/scalblnf.o \
    $(MUSL_OBJDIR)/src/math/log2l.o \
    $(MUSL_OBJDIR)/src/math/round.o \
    $(MUSL_OBJDIR)/src/math/fmaxl.o \
    $(MUSL_OBJDIR)/src/math/__sinl.o \
    $(MUSL_OBJDIR)/src/math/cosh.o \
    $(MUSL_OBJDIR)/src/math/sqrtf.o \
    $(MUSL_OBJDIR)/src/math/nextafterl.o \
    $(MUSL_OBJDIR)/src/math/rintl.o \
    $(MUSL_OBJDIR)/src/math/nextafterf.o \
    $(MUSL_OBJDIR)/src/math/sincosl.o \
    $(MUSL_OBJDIR)/src/math/modf.o \
    $(MUSL_OBJDIR)/src/math/sinl.o \
    $(MUSL_OBJDIR)/src/math/lround.o \
    $(MUSL_OBJDIR)/src/math/ceil.o \
    $(MUSL_OBJDIR)/src/math/log1pf.o \
    $(MUSL_OBJDIR)/src/math/lgammaf.o \
    $(MUSL_OBJDIR)/src/math/asinhf.o \
    $(MUSL_OBJDIR)/src/math/frexpl.o \
    $(MUSL_OBJDIR)/src/math/copysignf.o \
    $(MUSL_OBJDIR)/src/math/significandf.o \
    $(MUSL_OBJDIR)/src/math/fminf.o \
    $(MUSL_OBJDIR)/src/math/logf.o \
    $(MUSL_OBJDIR)/src/math/nearbyintl.o \
    $(MUSL_OBJDIR)/src/math/logl.o \
    $(MUSL_OBJDIR)/src/math/trunc.o \
    $(MUSL_OBJDIR)/src/math/__cosdf.o \
    $(MUSL_OBJDIR)/src/math/finitef.o \
    $(MUSL_OBJDIR)/src/math/lrintl.o \
    $(MUSL_OBJDIR)/src/math/remainderl.o \
    $(MUSL_OBJDIR)/src/math/fmax.o \
    $(MUSL_OBJDIR)/src/math/nextafter.o \
    $(MUSL_OBJDIR)/src/math/tgammaf.o \
    $(MUSL_OBJDIR)/src/math/significand.o \
    $(MUSL_OBJDIR)/src/math/fminl.o \
    $(MUSL_OBJDIR)/src/math/atanhf.o \
    $(MUSL_OBJDIR)/src/math/ilogbf.o \
    $(MUSL_OBJDIR)/src/math/hypot.o \
    $(MUSL_OBJDIR)/src/math/llrintl.o \
    $(MUSL_OBJDIR)/src/math/__expo2f.o \
    $(MUSL_OBJDIR)/src/math/ldexpf.o \
    $(MUSL_OBJDIR)/src/math/log10f.o \
    $(MUSL_OBJDIR)/src/math/lrintf.o \
    $(MUSL_OBJDIR)/src/math/__rem_pio2l.o \
    $(MUSL_OBJDIR)/src/math/jnf.o \
    $(MUSL_OBJDIR)/src/math/__signbitl.o \
    $(MUSL_OBJDIR)/src/math/log.o \
    $(MUSL_OBJDIR)/src/math/fabsf.o \
    $(MUSL_OBJDIR)/src/math/ceilf.o \
    $(MUSL_OBJDIR)/src/math/__sindf.o \
    $(MUSL_OBJDIR)/src/math/__cosl.o \
    $(MUSL_OBJDIR)/src/math/remquo.o \
    $(MUSL_OBJDIR)/src/math/erff.o \
    $(MUSL_OBJDIR)/src/math/fdiml.o \
    $(MUSL_OBJDIR)/src/math/coshl.o \
    $(MUSL_OBJDIR)/src/math/coshf.o \
    $(MUSL_OBJDIR)/src/math/fmaxf.o \
    $(MUSL_OBJDIR)/src/math/nearbyint.o \
    $(MUSL_OBJDIR)/src/math/__rem_pio2f.o \
    $(MUSL_OBJDIR)/src/math/scalbn.o \
    $(MUSL_OBJDIR)/src/math/remquol.o \
    $(MUSL_OBJDIR)/src/math/modff.o \
    $(MUSL_OBJDIR)/src/math/exp2.o \
    $(MUSL_OBJDIR)/src/math/llroundf.o \
    $(MUSL_OBJDIR)/src/math/llround.o \
    $(MUSL_OBJDIR)/src/math/tanhl.o \
    $(MUSL_OBJDIR)/src/math/atan.o \
    $(MUSL_OBJDIR)/src/math/floor.o \
    $(MUSL_OBJDIR)/src/math/tan.o \
    $(MUSL_OBJDIR)/src/math/__polevll.o \
    $(MUSL_OBJDIR)/src/math/tanl.o \
    $(MUSL_OBJDIR)/src/math/lroundl.o \
    $(MUSL_OBJDIR)/src/math/fmodf.o \
    $(MUSL_OBJDIR)/src/math/ilogbl.o \
    $(MUSL_OBJDIR)/src/math/acosf.o \
    $(MUSL_OBJDIR)/src/math/cbrt.o \
    $(MUSL_OBJDIR)/src/math/remquof.o \
    $(MUSL_OBJDIR)/src/math/sincos.o \
    $(MUSL_OBJDIR)/src/math/logbf.o \
    $(MUSL_OBJDIR)/src/math/scalbln.o \
    $(MUSL_OBJDIR)/src/math/cosf.o \
    $(MUSL_OBJDIR)/src/math/ldexp.o \
    $(MUSL_OBJDIR)/src/math/truncf.o \
    $(MUSL_OBJDIR)/src/math/pow.o \
    $(MUSL_OBJDIR)/src/math/expm1f.o \
    $(MUSL_OBJDIR)/src/math/floorl.o \
    $(MUSL_OBJDIR)/src/math/lrint.o \
    $(MUSL_OBJDIR)/src/math/scalb.o \
    $(MUSL_OBJDIR)/src/math/lgammaf_r.o \
    $(MUSL_OBJDIR)/src/math/atan2l.o \
    $(MUSL_OBJDIR)/src/math/cosl.o \
    $(MUSL_OBJDIR)/src/math/j1.o \
    $(MUSL_OBJDIR)/src/math/llroundl.o \
    $(MUSL_OBJDIR)/src/math/__fpclassify.o \
    $(MUSL_OBJDIR)/src/math/scalbnl.o \
    $(MUSL_OBJDIR)/src/math/sin.o \
    $(MUSL_OBJDIR)/src/math/expm1.o \
    $(MUSL_OBJDIR)/src/math/j0.o \
    $(MUSL_OBJDIR)/src/math/atanl.o \
    $(MUSL_OBJDIR)/src/math/rint.o \
    $(MUSL_OBJDIR)/src/math/scalbf.o \
    $(MUSL_OBJDIR)/src/math/__tandf.o \
    $(MUSL_OBJDIR)/src/math/fdim.o \
    $(MUSL_OBJDIR)/src/math/acoshl.o \
    $(MUSL_OBJDIR)/src/math/rintf.o \
    $(MUSL_OBJDIR)/src/math/log1pl.o \
    $(MUSL_OBJDIR)/src/math/log2f.o \
    $(MUSL_OBJDIR)/src/math/__invtrigl.o \
    $(MUSL_OBJDIR)/src/math/tgammal.o \
    $(MUSL_OBJDIR)/src/math/fmin.o \
    $(MUSL_OBJDIR)/src/math/logb.o \
    $(MUSL_OBJDIR)/src/math/expl.o \
    $(MUSL_OBJDIR)/src/math/remainder.o \
    $(MUSL_OBJDIR)/src/math/asinl.o \
    $(MUSL_OBJDIR)/src/math/j1f.o \
    $(MUSL_OBJDIR)/src/math/exp10.o \
    $(MUSL_OBJDIR)/src/unistd/setsid.o \
    $(MUSL_OBJDIR)/src/unistd/getpid.o \
    $(MUSL_OBJDIR)/src/unistd/posix_close.o \
    $(MUSL_OBJDIR)/src/unistd/getgroups.o \
    $(MUSL_OBJDIR)/src/unistd/ctermid.o \
    $(MUSL_OBJDIR)/src/unistd/dup.o \
    $(MUSL_OBJDIR)/src/unistd/getlogin.o \
    $(MUSL_OBJDIR)/src/unistd/rmdir.o \
    $(MUSL_OBJDIR)/src/unistd/setuid.o \
    $(MUSL_OBJDIR)/src/unistd/fdatasync.o \
    $(MUSL_OBJDIR)/src/unistd/setegid.o \
    $(MUSL_OBJDIR)/src/unistd/link.o \
    $(MUSL_OBJDIR)/src/unistd/pipe2.o \
    $(MUSL_OBJDIR)/src/unistd/setpgrp.o \
    $(MUSL_OBJDIR)/src/unistd/lchown.o \
    $(MUSL_OBJDIR)/src/unistd/faccessat.o \
    $(MUSL_OBJDIR)/src/unistd/writev.o \
    $(MUSL_OBJDIR)/src/unistd/nice.o \
    $(MUSL_OBJDIR)/src/unistd/pwritev.o \
    $(MUSL_OBJDIR)/src/unistd/getsid.o \
    $(MUSL_OBJDIR)/src/unistd/access.o \
    $(MUSL_OBJDIR)/src/unistd/pipe.o \
    $(MUSL_OBJDIR)/src/unistd/geteuid.o \
    $(MUSL_OBJDIR)/src/unistd/pause.o \
    $(MUSL_OBJDIR)/src/unistd/chown.o \
    $(MUSL_OBJDIR)/src/unistd/setregid.o \
    $(MUSL_OBJDIR)/src/unistd/setxid.o \
    $(MUSL_OBJDIR)/src/unistd/symlinkat.o \
    $(MUSL_OBJDIR)/src/unistd/sleep.o \
    $(MUSL_OBJDIR)/src/unistd/ftruncate.o \
    $(MUSL_OBJDIR)/src/unistd/readv.o \
    $(MUSL_OBJDIR)/src/unistd/dup3.o \
    $(MUSL_OBJDIR)/src/unistd/unlink.o \
    $(MUSL_OBJDIR)/src/unistd/fchown.o \
    $(MUSL_OBJDIR)/src/unistd/close.o \
    $(MUSL_OBJDIR)/src/unistd/alarm.o \
    $(MUSL_OBJDIR)/src/unistd/tcgetpgrp.o \
    $(MUSL_OBJDIR)/src/unistd/getcwd.o \
    $(MUSL_OBJDIR)/src/unistd/preadv.o \
    $(MUSL_OBJDIR)/src/unistd/getlogin_r.o \
    $(MUSL_OBJDIR)/src/unistd/ttyname_r.o \
    $(MUSL_OBJDIR)/src/unistd/isatty.o \
    $(MUSL_OBJDIR)/src/unistd/getegid.o \
    $(MUSL_OBJDIR)/src/unistd/unlinkat.o \
    $(MUSL_OBJDIR)/src/unistd/dup2.o \
    $(MUSL_OBJDIR)/src/unistd/pwrite.o \
    $(MUSL_OBJDIR)/src/unistd/setgid.o \
    $(MUSL_OBJDIR)/src/unistd/setreuid.o \
    $(MUSL_OBJDIR)/src/unistd/readlinkat.o \
    $(MUSL_OBJDIR)/src/unistd/fchownat.o \
    $(MUSL_OBJDIR)/src/unistd/fchdir.o \
    $(MUSL_OBJDIR)/src/unistd/acct.o \
    $(MUSL_OBJDIR)/src/unistd/sync.o \
    $(MUSL_OBJDIR)/src/unistd/truncate.o \
    $(MUSL_OBJDIR)/src/unistd/setresgid.o \
    $(MUSL_OBJDIR)/src/unistd/fsync.o \
    $(MUSL_OBJDIR)/src/unistd/getgid.o \
    $(MUSL_OBJDIR)/src/unistd/ttyname.o \
    $(MUSL_OBJDIR)/src/unistd/getpgrp.o \
    $(MUSL_OBJDIR)/src/unistd/renameat.o \
    $(MUSL_OBJDIR)/src/unistd/readlink.o \
    $(MUSL_OBJDIR)/src/unistd/setpgid.o \
    $(MUSL_OBJDIR)/src/unistd/seteuid.o \
    $(MUSL_OBJDIR)/src/unistd/linkat.o \
    $(MUSL_OBJDIR)/src/unistd/lseek.o \
    $(MUSL_OBJDIR)/src/unistd/write.o \
    $(MUSL_OBJDIR)/src/unistd/read.o \
    $(MUSL_OBJDIR)/src/unistd/ualarm.o \
    $(MUSL_OBJDIR)/src/unistd/getppid.o \
    $(MUSL_OBJDIR)/src/unistd/chdir.o \
    $(MUSL_OBJDIR)/src/unistd/getuid.o \
    $(MUSL_OBJDIR)/src/unistd/setresuid.o \
    $(MUSL_OBJDIR)/src/unistd/getpgid.o \
    $(MUSL_OBJDIR)/src/unistd/gethostname.o \
    $(MUSL_OBJDIR)/src/unistd/_exit.o \
    $(MUSL_OBJDIR)/src/unistd/symlink.o \
    $(MUSL_OBJDIR)/src/unistd/usleep.o \
    $(MUSL_OBJDIR)/src/unistd/tcsetpgrp.o \
    $(MUSL_OBJDIR)/src/unistd/pread.o \
    $(MUSL_OBJDIR)/src/temp/mkdtemp.o \
    $(MUSL_OBJDIR)/src/temp/mkstemps.o \
    $(MUSL_OBJDIR)/src/temp/mkstemp.o \
    $(MUSL_OBJDIR)/src/temp/mkostemps.o \
    $(MUSL_OBJDIR)/src/temp/mktemp.o \
    $(MUSL_OBJDIR)/src/temp/mkostemp.o \
    $(MUSL_OBJDIR)/src/temp/__randname.o \
    $(MUSL_OBJDIR)/src/crypt/crypt_sha512.o \
    $(MUSL_OBJDIR)/src/crypt/crypt_sha256.o \
    $(MUSL_OBJDIR)/src/crypt/crypt_r.o \
    $(MUSL_OBJDIR)/src/crypt/crypt_blowfish.o \
    $(MUSL_OBJDIR)/src/crypt/crypt.o \
    $(MUSL_OBJDIR)/src/crypt/crypt_des.o \
    $(MUSL_OBJDIR)/src/crypt/encrypt.o \
    $(MUSL_OBJDIR)/src/crypt/crypt_md5.o \
    $(MUSL_OBJDIR)/src/prng/lcong48.o \
    $(MUSL_OBJDIR)/src/prng/rand_r.o \
    $(MUSL_OBJDIR)/src/prng/__seed48.o \
    $(MUSL_OBJDIR)/src/prng/rand.o \
    $(MUSL_OBJDIR)/src/prng/seed48.o \
    $(MUSL_OBJDIR)/src/prng/random.o \
    $(MUSL_OBJDIR)/src/prng/__rand48_step.o \
    $(MUSL_OBJDIR)/src/prng/mrand48.o \
    $(MUSL_OBJDIR)/src/prng/drand48.o \
    $(MUSL_OBJDIR)/src/prng/srand48.o \
    $(MUSL_OBJDIR)/src/prng/lrand48.o \
    $(MUSL_OBJDIR)/src/ldso/tlsdesc.o \
    $(MUSL_OBJDIR)/src/ldso/dlopen.o \
    $(MUSL_OBJDIR)/src/ldso/dl_iterate_phdr.o \
    $(MUSL_OBJDIR)/src/ldso/dlinfo.o \
    $(MUSL_OBJDIR)/src/ldso/dladdr.o \
    $(MUSL_OBJDIR)/src/ldso/dlclose.o \
    $(MUSL_OBJDIR)/src/ldso/__dlsym.o \
    $(MUSL_OBJDIR)/src/ldso/dlerror.o \
    $(MUSL_OBJDIR)/src/ldso/dlsym.o \
    $(MUSL_OBJDIR)/src/fenv/fesetexceptflag.o \
    $(MUSL_OBJDIR)/src/fenv/fenv.o \
    $(MUSL_OBJDIR)/src/fenv/fesetround.o \
    $(MUSL_OBJDIR)/src/fenv/__flt_rounds.o \
    $(MUSL_OBJDIR)/src/fenv/feholdexcept.o \
    $(MUSL_OBJDIR)/src/fenv/fegetexceptflag.o \
    $(MUSL_OBJDIR)/src/fenv/feupdateenv.o \
    $(MUSL_OBJDIR)/src/misc/uname.o \
    $(MUSL_OBJDIR)/src/misc/ffsl.o \
    $(MUSL_OBJDIR)/src/misc/issetugid.o \
    $(MUSL_OBJDIR)/src/misc/mntent.o \
    $(MUSL_OBJDIR)/src/misc/getauxval.o \
    $(MUSL_OBJDIR)/src/misc/setdomainname.o \
    $(MUSL_OBJDIR)/src/misc/forkpty.o \
    $(MUSL_OBJDIR)/src/misc/ffsll.o \
    $(MUSL_OBJDIR)/src/misc/syslog.o \
    $(MUSL_OBJDIR)/src/misc/getpriority.o \
    $(MUSL_OBJDIR)/src/misc/gethostid.o \
    $(MUSL_OBJDIR)/src/misc/setpriority.o \
    $(MUSL_OBJDIR)/src/misc/getrlimit.o \
    $(MUSL_OBJDIR)/src/misc/a64l.o \
    $(MUSL_OBJDIR)/src/misc/nftw.o \
    $(MUSL_OBJDIR)/src/misc/getresgid.o \
    $(MUSL_OBJDIR)/src/misc/ffs.o \
    $(MUSL_OBJDIR)/src/misc/ptsname.o \
    $(MUSL_OBJDIR)/src/misc/openpty.o \
    $(MUSL_OBJDIR)/src/misc/pty.o \
    $(MUSL_OBJDIR)/src/misc/ioctl.o \
    $(MUSL_OBJDIR)/src/misc/lockf.o \
    $(MUSL_OBJDIR)/src/misc/basename.o \
    $(MUSL_OBJDIR)/src/misc/getdomainname.o \
    $(MUSL_OBJDIR)/src/misc/wordexp.o \
    $(MUSL_OBJDIR)/src/misc/getopt.o \
    $(MUSL_OBJDIR)/src/misc/setrlimit.o \
    $(MUSL_OBJDIR)/src/misc/getresuid.o \
    $(MUSL_OBJDIR)/src/misc/getsubopt.o \
    $(MUSL_OBJDIR)/src/misc/get_current_dir_name.o \
    $(MUSL_OBJDIR)/src/misc/dirname.o \
    $(MUSL_OBJDIR)/src/misc/initgroups.o \
    $(MUSL_OBJDIR)/src/misc/realpath.o \
    $(MUSL_OBJDIR)/src/misc/getopt_long.o \
    $(MUSL_OBJDIR)/src/misc/fmtmsg.o \
    $(MUSL_OBJDIR)/src/misc/login_tty.o \
    $(MUSL_OBJDIR)/src/misc/getrusage.o \
    $(MUSL_OBJDIR)/src/misc/syscall.o \
    $(MUSL_OBJDIR)/src/passwd/putspent.o \
    $(MUSL_OBJDIR)/src/passwd/fgetpwent.o \
    $(MUSL_OBJDIR)/src/passwd/getgr_r.o \
    $(MUSL_OBJDIR)/src/passwd/lckpwdf.o \
    $(MUSL_OBJDIR)/src/passwd/getgrouplist.o \
    $(MUSL_OBJDIR)/src/passwd/putpwent.o \
    $(MUSL_OBJDIR)/src/passwd/getgrent.o \
    $(MUSL_OBJDIR)/src/passwd/fgetspent.o \
    $(MUSL_OBJDIR)/src/passwd/getspnam.o \
    $(MUSL_OBJDIR)/src/passwd/getspent.o \
    $(MUSL_OBJDIR)/src/passwd/getpwent.o \
    $(MUSL_OBJDIR)/src/passwd/getspnam_r.o \
    $(MUSL_OBJDIR)/src/passwd/getpw_a.o \
    $(MUSL_OBJDIR)/src/passwd/getgr_a.o \
    $(MUSL_OBJDIR)/src/passwd/getgrent_a.o \
    $(MUSL_OBJDIR)/src/passwd/putgrent.o \
    $(MUSL_OBJDIR)/src/passwd/fgetgrent.o \
    $(MUSL_OBJDIR)/src/passwd/getpwent_a.o \
    $(MUSL_OBJDIR)/src/passwd/nscd_query.o \
    $(MUSL_OBJDIR)/src/passwd/getpw_r.o \
    $(MUSL_OBJDIR)/src/setjmp/setjmp.o \
    $(MUSL_OBJDIR)/src/setjmp/longjmp.o \
    $(MUSL_OBJDIR)/src/regex/tre-mem.o \
    $(MUSL_OBJDIR)/src/regex/regcomp.o \
    $(MUSL_OBJDIR)/src/regex/fnmatch.o \
    $(MUSL_OBJDIR)/src/regex/regexec.o \
    $(MUSL_OBJDIR)/src/regex/regerror.o \
    $(MUSL_OBJDIR)/src/regex/glob.o \
    $(MUSL_OBJDIR)/src/ctype/isblank.o \
    $(MUSL_OBJDIR)/src/ctype/__ctype_b_loc.o \
    $(MUSL_OBJDIR)/src/ctype/iswalnum.o \
    $(MUSL_OBJDIR)/src/ctype/iswblank.o \
    $(MUSL_OBJDIR)/src/ctype/isdigit.o \
    $(MUSL_OBJDIR)/src/ctype/isalnum.o \
    $(MUSL_OBJDIR)/src/ctype/wcwidth.o \
    $(MUSL_OBJDIR)/src/ctype/iswalpha.o \
    $(MUSL_OBJDIR)/src/ctype/iswpunct.o \
    $(MUSL_OBJDIR)/src/ctype/iswcntrl.o \
    $(MUSL_OBJDIR)/src/ctype/iscntrl.o \
    $(MUSL_OBJDIR)/src/ctype/isxdigit.o \
    $(MUSL_OBJDIR)/src/ctype/iswgraph.o \
    $(MUSL_OBJDIR)/src/ctype/isspace.o \
    $(MUSL_OBJDIR)/src/ctype/isprint.o \
    $(MUSL_OBJDIR)/src/ctype/__ctype_get_mb_cur_max.o \
    $(MUSL_OBJDIR)/src/ctype/iswlower.o \
    $(MUSL_OBJDIR)/src/ctype/iswxdigit.o \
    $(MUSL_OBJDIR)/src/ctype/iswprint.o \
    $(MUSL_OBJDIR)/src/ctype/tolower.o \
    $(MUSL_OBJDIR)/src/ctype/toupper.o \
    $(MUSL_OBJDIR)/src/ctype/wcswidth.o \
    $(MUSL_OBJDIR)/src/ctype/toascii.o \
    $(MUSL_OBJDIR)/src/ctype/isascii.o \
    $(MUSL_OBJDIR)/src/ctype/iswdigit.o \
    $(MUSL_OBJDIR)/src/ctype/towctrans.o \
    $(MUSL_OBJDIR)/src/ctype/iswspace.o \
    $(MUSL_OBJDIR)/src/ctype/ispunct.o \
    $(MUSL_OBJDIR)/src/ctype/iswupper.o \
    $(MUSL_OBJDIR)/src/ctype/isalpha.o \
    $(MUSL_OBJDIR)/src/ctype/__ctype_tolower_loc.o \
    $(MUSL_OBJDIR)/src/ctype/isupper.o \
    $(MUSL_OBJDIR)/src/ctype/islower.o \
    $(MUSL_OBJDIR)/src/ctype/__ctype_toupper_loc.o \
    $(MUSL_OBJDIR)/src/ctype/isgraph.o \
    $(MUSL_OBJDIR)/src/ctype/iswctype.o \
    $(MUSL_OBJDIR)/src/ctype/wctrans.o \
    $(MUSL_OBJDIR)/src/legacy/utmpx.o \
    $(MUSL_OBJDIR)/src/legacy/daemon.o \
    $(MUSL_OBJDIR)/src/legacy/cuserid.o \
    $(MUSL_OBJDIR)/src/legacy/ftw.o \
    $(MUSL_OBJDIR)/src/legacy/lutimes.o \
    $(MUSL_OBJDIR)/src/legacy/getpagesize.o \
    $(MUSL_OBJDIR)/src/legacy/futimes.o \
    $(MUSL_OBJDIR)/src/legacy/getpass.o \
    $(MUSL_OBJDIR)/src/legacy/getdtablesize.o \
    $(MUSL_OBJDIR)/src/legacy/err.o \
    $(MUSL_OBJDIR)/src/legacy/getusershell.o \
    $(MUSL_OBJDIR)/src/legacy/euidaccess.o \
    $(MUSL_OBJDIR)/src/legacy/valloc.o \
    $(MUSL_OBJDIR)/src/legacy/getloadavg.o \
    $(MUSL_OBJDIR)/src/legacy/ulimit.o \
    $(MUSL_OBJDIR)/src/legacy/isastream.o \
    $(MUSL_OBJDIR)/src/aio/aio_suspend.o \
    $(MUSL_OBJDIR)/src/aio/aio.o \
    $(MUSL_OBJDIR)/src/aio/lio_listio.o \
    $(MUSL_OBJDIR)/src/mq/mq_setattr.o \
    $(MUSL_OBJDIR)/src/mq/mq_close.o \
    $(MUSL_OBJDIR)/src/mq/mq_send.o \
    $(MUSL_OBJDIR)/src/mq/mq_getattr.o \
    $(MUSL_OBJDIR)/src/mq/mq_open.o \
    $(MUSL_OBJDIR)/src/mq/mq_unlink.o \
    $(MUSL_OBJDIR)/src/mq/mq_timedsend.o \
    $(MUSL_OBJDIR)/src/mq/mq_receive.o \
    $(MUSL_OBJDIR)/src/mq/mq_notify.o \
    $(MUSL_OBJDIR)/src/mq/mq_timedreceive.o \
    $(MUSL_OBJDIR)/src/process/execvp.o \
    $(MUSL_OBJDIR)/src/process/waitpid.o \
    $(MUSL_OBJDIR)/src/process/posix_spawnattr_init.o \
    $(MUSL_OBJDIR)/src/process/posix_spawn_file_actions_addopen.o \
    $(MUSL_OBJDIR)/src/process/posix_spawn_file_actions_addclose.o \
    $(MUSL_OBJDIR)/src/process/posix_spawnattr_setsigmask.o \
    $(MUSL_OBJDIR)/src/process/posix_spawnattr_destroy.o \
    $(MUSL_OBJDIR)/src/process/posix_spawnattr_sched.o \
    $(MUSL_OBJDIR)/src/process/posix_spawnattr_getpgroup.o \
    $(MUSL_OBJDIR)/src/process/execve.o \
    $(MUSL_OBJDIR)/src/process/execl.o \
    $(MUSL_OBJDIR)/src/process/fork.o \
    $(MUSL_OBJDIR)/src/process/posix_spawnattr_setsigdefault.o \
    $(MUSL_OBJDIR)/src/process/execle.o \
    $(MUSL_OBJDIR)/src/process/posix_spawnattr_getsigdefault.o \
    $(MUSL_OBJDIR)/src/process/vfork.o \
    $(MUSL_OBJDIR)/src/process/posix_spawnattr_setpgroup.o \
    $(MUSL_OBJDIR)/src/process/posix_spawnattr_getsigmask.o \
    $(MUSL_OBJDIR)/src/process/posix_spawnp.o \
    $(MUSL_OBJDIR)/src/process/execv.o \
    $(MUSL_OBJDIR)/src/process/wait.o \
    $(MUSL_OBJDIR)/src/process/posix_spawn_file_actions_adddup2.o \
    $(MUSL_OBJDIR)/src/process/system.o \
    $(MUSL_OBJDIR)/src/process/posix_spawn.o \
    $(MUSL_OBJDIR)/src/process/posix_spawnattr_setflags.o \
    $(MUSL_OBJDIR)/src/process/waitid.o \
    $(MUSL_OBJDIR)/src/process/posix_spawn_file_actions_init.o \
    $(MUSL_OBJDIR)/src/process/posix_spawn_file_actions_destroy.o \
    $(MUSL_OBJDIR)/src/process/execlp.o \
    $(MUSL_OBJDIR)/src/process/fexecve.o \
    $(MUSL_OBJDIR)/src/process/posix_spawnattr_getflags.o \
    $(MUSL_OBJDIR)/src/stdlib/ecvt.o \
    $(MUSL_OBJDIR)/src/stdlib/wcstol.o \
    $(MUSL_OBJDIR)/src/stdlib/qsort.o \
    $(MUSL_OBJDIR)/src/stdlib/ldiv.o \
    $(MUSL_OBJDIR)/src/stdlib/wcstod.o \
    $(MUSL_OBJDIR)/src/stdlib/atoll.o \
    $(MUSL_OBJDIR)/src/stdlib/div.o \
    $(MUSL_OBJDIR)/src/stdlib/strtol.o \
    $(MUSL_OBJDIR)/src/stdlib/imaxabs.o \
    $(MUSL_OBJDIR)/src/stdlib/abs.o \
    $(MUSL_OBJDIR)/src/stdlib/bsearch.o \
    $(MUSL_OBJDIR)/src/stdlib/strtod.o \
    $(MUSL_OBJDIR)/src/stdlib/atoi.o \
    $(MUSL_OBJDIR)/src/stdlib/fcvt.o \
    $(MUSL_OBJDIR)/src/stdlib/atol.o \
    $(MUSL_OBJDIR)/src/stdlib/atof.o \
    $(MUSL_OBJDIR)/src/stdlib/llabs.o \
    $(MUSL_OBJDIR)/src/stdlib/imaxdiv.o \
    $(MUSL_OBJDIR)/src/stdlib/gcvt.o \
    $(MUSL_OBJDIR)/src/stdlib/lldiv.o \
    $(MUSL_OBJDIR)/src/stdlib/labs.o \
    $(MUSL_OBJDIR)/src/errno/__errno_location.o \
    $(MUSL_OBJDIR)/src/errno/strerror.o \
    $(MUSL_OBJDIR)/src/signal/setitimer.o \
    $(MUSL_OBJDIR)/src/signal/sighold.o \
    $(MUSL_OBJDIR)/src/signal/sigsetjmp.o \
    $(MUSL_OBJDIR)/src/signal/sigsuspend.o \
    $(MUSL_OBJDIR)/src/signal/sigfillset.o \
    $(MUSL_OBJDIR)/src/signal/sigaction.o \
    $(MUSL_OBJDIR)/src/signal/raise.o \
    $(MUSL_OBJDIR)/src/signal/psignal.o \
    $(MUSL_OBJDIR)/src/signal/sigqueue.o \
    $(MUSL_OBJDIR)/src/signal/killpg.o \
    $(MUSL_OBJDIR)/src/signal/sigrelse.o \
    $(MUSL_OBJDIR)/src/signal/signal.o \
    $(MUSL_OBJDIR)/src/signal/restore.o \
    $(MUSL_OBJDIR)/src/signal/sigignore.o \
    $(MUSL_OBJDIR)/src/signal/sigwait.o \
    $(MUSL_OBJDIR)/src/signal/psiginfo.o \
    $(MUSL_OBJDIR)/src/signal/sigemptyset.o \
    $(MUSL_OBJDIR)/src/signal/sigpending.o \
    $(MUSL_OBJDIR)/src/signal/sigrtmax.o \
    $(MUSL_OBJDIR)/src/signal/kill.o \
    $(MUSL_OBJDIR)/src/signal/sigrtmin.o \
    $(MUSL_OBJDIR)/src/signal/sigorset.o \
    $(MUSL_OBJDIR)/src/signal/sigaltstack.o \
    $(MUSL_OBJDIR)/src/signal/getitimer.o \
    $(MUSL_OBJDIR)/src/signal/sigsetjmp_tail.o \
    $(MUSL_OBJDIR)/src/signal/siglongjmp.o \
    $(MUSL_OBJDIR)/src/signal/sigtimedwait.o \
    $(MUSL_OBJDIR)/src/signal/block.o \
    $(MUSL_OBJDIR)/src/signal/sigdelset.o \
    $(MUSL_OBJDIR)/src/signal/sigwaitinfo.o \
    $(MUSL_OBJDIR)/src/signal/sigaddset.o \
    $(MUSL_OBJDIR)/src/signal/sigprocmask.o \
    $(MUSL_OBJDIR)/src/signal/sigisemptyset.o \
    $(MUSL_OBJDIR)/src/signal/siginterrupt.o \
    $(MUSL_OBJDIR)/src/signal/sigandset.o \
    $(MUSL_OBJDIR)/src/signal/sigismember.o \
    $(MUSL_OBJDIR)/src/signal/sigset.o \
    $(MUSL_OBJDIR)/src/signal/sigpause.o \
    $(MUSL_OBJDIR)/src/dirent/seekdir.o \
    $(MUSL_OBJDIR)/src/dirent/telldir.o \
    $(MUSL_OBJDIR)/src/dirent/dirfd.o \
    $(MUSL_OBJDIR)/src/dirent/readdir_r.o \
    $(MUSL_OBJDIR)/src/dirent/fdopendir.o \
    $(MUSL_OBJDIR)/src/dirent/readdir.o \
    $(MUSL_OBJDIR)/src/dirent/opendir.o \
    $(MUSL_OBJDIR)/src/dirent/__getdents.o \
    $(MUSL_OBJDIR)/src/dirent/scandir.o \
    $(MUSL_OBJDIR)/src/dirent/rewinddir.o \
    $(MUSL_OBJDIR)/src/dirent/closedir.o \
    $(MUSL_OBJDIR)/src/dirent/alphasort.o \
    $(MUSL_OBJDIR)/src/dirent/versionsort.o \
    $(MUSL_OBJDIR)/src/time/getdate.o \
    $(MUSL_OBJDIR)/src/time/clock.o \
    $(MUSL_OBJDIR)/src/time/wcsftime.o \
    $(MUSL_OBJDIR)/src/time/timegm.o \
    $(MUSL_OBJDIR)/src/time/timer_getoverrun.o \
    $(MUSL_OBJDIR)/src/time/asctime.o \
    $(MUSL_OBJDIR)/src/time/__tz.o \
    $(MUSL_OBJDIR)/src/time/gmtime.o \
    $(MUSL_OBJDIR)/src/time/timer_settime.o \
    $(MUSL_OBJDIR)/src/time/localtime_r.o \
    $(MUSL_OBJDIR)/src/time/difftime.o \
    $(MUSL_OBJDIR)/src/time/timer_create.o \
    $(MUSL_OBJDIR)/src/time/ctime_r.o \
    $(MUSL_OBJDIR)/src/time/clock_settime.o \
    $(MUSL_OBJDIR)/src/time/clock_getcpuclockid.o \
    $(MUSL_OBJDIR)/src/time/timer_delete.o \
    $(MUSL_OBJDIR)/src/time/__month_to_secs.o \
    $(MUSL_OBJDIR)/src/time/ftime.o \
    $(MUSL_OBJDIR)/src/time/ctime.o \
    $(MUSL_OBJDIR)/src/time/__asctime.o \
    $(MUSL_OBJDIR)/src/time/strftime.o \
    $(MUSL_OBJDIR)/src/time/time.o \
    $(MUSL_OBJDIR)/src/time/timer_gettime.o \
    $(MUSL_OBJDIR)/src/time/__secs_to_tm.o \
    $(MUSL_OBJDIR)/src/time/times.o \
    $(MUSL_OBJDIR)/src/time/localtime.o \
    $(MUSL_OBJDIR)/src/time/strptime.o \
    $(MUSL_OBJDIR)/src/time/asctime_r.o \
    $(MUSL_OBJDIR)/src/time/__map_file.o \
    $(MUSL_OBJDIR)/src/time/utime.o \
    $(MUSL_OBJDIR)/src/time/clock_getres.o \
    $(MUSL_OBJDIR)/src/time/clock_nanosleep.o \
    $(MUSL_OBJDIR)/src/time/mktime.o \
    $(MUSL_OBJDIR)/src/time/nanosleep.o \
    $(MUSL_OBJDIR)/src/time/timespec_get.o \
    $(MUSL_OBJDIR)/src/time/clock_gettime.o \
    $(MUSL_OBJDIR)/src/time/gmtime_r.o \
    $(MUSL_OBJDIR)/src/time/__year_to_secs.o \
    $(MUSL_OBJDIR)/src/time/__tm_to_secs.o \
    $(MUSL_OBJDIR)/src/time/gettimeofday.o \
    $(MUSL_OBJDIR)/ldso/dynlink.o \
    $(MUSL_OBJDIR)/ldso/dlstart.o

libc: $(MUSL_LIBC) $(MUSL_CRT_OBJS)
	cp -R $(MUSL_SUBDIR)/include $(BUILDDIR)

$(MUSL_LIBC): $(MUSL_OBJS)
	@echo $(AR) $(ARFLAGS) $@
	@$(ARCHIVE)

$(MUSL_OBJDIR)/%.o: $(MUSL_SUBDIR)/%.c
	$(MUSL_COMPILE)

# CRT Objects
$(LIBDIR)/Scrt1.o: $(MUSL_SUBDIR)/crt/Scrt1.c
	$(MUSL_COMPILE) -DCRT
$(LIBDIR)/ccrt1.o: $(MUSL_SUBDIR)/crt/crt1.c
	$(MUSL_COMPILE) -DCRT
$(LIBDIR)/rcrt1.o: $(MUSL_SUBDIR)/crt/rcrt1.c
	$(MUSL_COMPILE) -DCRT
$(LIBDIR)/crti.o: $(MUSL_SUBDIR)/crt/x86_64/crti.s
	$(MUSL_COMPILE) -DCRT
$(LIBDIR)/crtn.o: $(MUSL_SUBDIR)/crt/x86_64/crtn.s
	$(MUSL_COMPILE) -DCRT
