#ifdef _CS_PATH
	{"PATH",	_CS_PATH},
#endif
#ifdef _CS_POSIX_V7_ILP32_OFF32_CFLAGS
	{"POSIX_V7_ILP32_OFF32_CFLAGS",	_CS_POSIX_V7_ILP32_OFF32_CFLAGS},
#endif
#ifdef _CS_POSIX_V7_ILP32_OFF32_LDFLAGS
	{"POSIX_V7_ILP32_OFF32_LDFLAGS",	_CS_POSIX_V7_ILP32_OFF32_LDFLAGS},
#endif
#ifdef _CS_POSIX_V7_ILP32_OFF32_LIBS
	{"POSIX_V7_ILP32_OFF32_LIBS",	_CS_POSIX_V7_ILP32_OFF32_LIBS},
#endif
#ifdef _CS_POSIX_V7_ILP32_OFFBIG_CFLAGS
	{"POSIX_V7_ILP32_OFFBIG_CFLAGS",	_CS_POSIX_V7_ILP32_OFFBIG_CFLAGS},
#endif
#ifdef _CS_POSIX_V7_ILP32_OFFBIG_LDFLAGS
	{"POSIX_V7_ILP32_OFFBIG_LDFLAGS",	_CS_POSIX_V7_ILP32_OFFBIG_LDFLAGS},
#endif
#ifdef _CS_POSIX_V7_ILP32_OFFBIG_LIBS
	{"POSIX_V7_ILP32_OFFBIG_LIBS",	_CS_POSIX_V7_ILP32_OFFBIG_LIBS},
#endif
#ifdef _CS_POSIX_V7_LP64_OFF64_CFLAGS
	{"POSIX_V7_LP64_OFF64_CFLAGS",	_CS_POSIX_V7_LP64_OFF64_CFLAGS},
#endif
#ifdef _CS_POSIX_V7_LP64_OFF64_LDFLAGS
	{"POSIX_V7_LP64_OFF64_LDFLAGS",	_CS_POSIX_V7_LP64_OFF64_LDFLAGS},
#endif
#ifdef _CS_POSIX_V7_LP64_OFF64_LIBS
	{"POSIX_V7_LP64_OFF64_LIBS",	_CS_POSIX_V7_LP64_OFF64_LIBS},
#endif
#ifdef _CS_POSIX_V7_LPBIG_OFFBIG_CFLAGS
	{"POSIX_V7_LPBIG_OFFBIG_CFLAGS",	_CS_POSIX_V7_LPBIG_OFFBIG_CFLAGS},
#endif
#ifdef _CS_POSIX_V7_LPBIG_OFFBIG_LDFLAGS
	{"POSIX_V7_LPBIG_OFFBIG_LDFLAGS",	_CS_POSIX_V7_LPBIG_OFFBIG_LDFLAGS},
#endif
#ifdef _CS_POSIX_V7_LPBIG_OFFBIG_LIBS
	{"POSIX_V7_LPBIG_OFFBIG_LIBS",	_CS_POSIX_V7_LPBIG_OFFBIG_LIBS},
#endif
#ifdef _CS_POSIX_V7_THREADS_CFLAGS
	{"POSIX_V7_THREADS_CFLAGS",	_CS_POSIX_V7_THREADS_CFLAGS},
#endif
#ifdef _CS_POSIX_V7_THREADS_LDFLAGS
	{"POSIX_V7_THREADS_LDFLAGS",	_CS_POSIX_V7_THREADS_LDFLAGS},
#endif
#ifdef _CS_POSIX_V7_WIDTH_RESTRICTED_ENVS
	{"POSIX_V7_WIDTH_RESTRICTED_ENVS",	_CS_POSIX_V7_WIDTH_RESTRICTED_ENVS},
#endif
#ifdef _CS_V7_ENV
	{"V7_ENV",	_CS_V7_ENV},
#endif
