#ifdef _POSIX_CLOCKRES_MIN
	{"_POSIX_CLOCKRES_MIN",	_POSIX_CLOCKRES_MIN},
#endif
#ifdef _POSIX_AIO_LISTIO_MAX
	{"_POSIX_AIO_LISTIO_MAX",	_POSIX_AIO_LISTIO_MAX},
#endif
#ifdef _POSIX_AIO_MAX
	{"_POSIX_AIO_MAX",	_POSIX_AIO_MAX},
#endif
#ifdef _POSIX_ARG_MAX
	{"_POSIX_ARG_MAX",	_POSIX_ARG_MAX},
#endif
#ifdef _POSIX_CHILD_MAX
	{"_POSIX_CHILD_MAX",	_POSIX_CHILD_MAX},
#endif
#ifdef _POSIX_DELAYTIMER_MAX
	{"_POSIX_DELAYTIMER_MAX",	_POSIX_DELAYTIMER_MAX},
#endif
#ifdef _POSIX_HOST_NAME_MAX
	{"_POSIX_HOST_NAME_MAX",	_POSIX_HOST_NAME_MAX},
#endif
#ifdef _POSIX_LINK_MAX
	{"_POSIX_LINK_MAX",	_POSIX_LINK_MAX},
#endif
#ifdef _POSIX_LOGIN_NAME_MAX
	{"_POSIX_LOGIN_NAME_MAX",	_POSIX_LOGIN_NAME_MAX},
#endif
#ifdef _POSIX_MAX_CANON
	{"_POSIX_MAX_CANON",	_POSIX_MAX_CANON},
#endif
#ifdef _POSIX_MAX_INPUT
	{"_POSIX_MAX_INPUT",	_POSIX_MAX_INPUT},
#endif
#ifdef _POSIX_MQ_OPEN_MAX
	{"_POSIX_MQ_OPEN_MAX",	_POSIX_MQ_OPEN_MAX},
#endif
#ifdef _POSIX_MQ_PRIO_MAX
	{"_POSIX_MQ_PRIO_MAX",	_POSIX_MQ_PRIO_MAX},
#endif
#ifdef _POSIX_NAME_MAX
	{"_POSIX_NAME_MAX",	_POSIX_NAME_MAX},
#endif
#ifdef _POSIX_NGROUPS_MAX
	{"_POSIX_NGROUPS_MAX",	_POSIX_NGROUPS_MAX},
#endif
#ifdef _POSIX_OPEN_MAX
	{"_POSIX_OPEN_MAX",	_POSIX_OPEN_MAX},
#endif
#ifdef _POSIX_PATH_MAX
	{"_POSIX_PATH_MAX",	_POSIX_PATH_MAX},
#endif
#ifdef _POSIX_PIPE_BUF
	{"_POSIX_PIPE_BUF",	_POSIX_PIPE_BUF},
#endif
#ifdef _POSIX_RE_DUP_MAX
	{"_POSIX_RE_DUP_MAX",	_POSIX_RE_DUP_MAX},
#endif
#ifdef _POSIX_RTSIG_MAX
	{"_POSIX_RTSIG_MAX",	_POSIX_RTSIG_MAX},
#endif
#ifdef _POSIX_SEM_NSEMS_MAX
	{"_POSIX_SEM_NSEMS_MAX",	_POSIX_SEM_NSEMS_MAX},
#endif
#ifdef _POSIX_SEM_VALUE_MAX
	{"_POSIX_SEM_VALUE_MAX",	_POSIX_SEM_VALUE_MAX},
#endif
#ifdef _POSIX_SIGQUEUE_MAX
	{"_POSIX_SIGQUEUE_MAX",	_POSIX_SIGQUEUE_MAX},
#endif
#ifdef _POSIX_SSIZE_MAX
	{"_POSIX_SSIZE_MAX",	_POSIX_SSIZE_MAX},
#endif
#ifdef _POSIX_SS_REPL_MAX
	{"_POSIX_SS_REPL_MAX",	_POSIX_SS_REPL_MAX},
#endif
#ifdef _POSIX_STREAM_MAX
	{"_POSIX_STREAM_MAX",	_POSIX_STREAM_MAX},
#endif
#ifdef _POSIX_SYMLINK_MAX
	{"_POSIX_SYMLINK_MAX",	_POSIX_SYMLINK_MAX},
#endif
#ifdef _POSIX_SYMLOOP_MAX
	{"_POSIX_SYMLOOP_MAX",	_POSIX_SYMLOOP_MAX},
#endif
#ifdef _POSIX_THREAD_DESTRUCTOR_ITERATIONS
	{"_POSIX_THREAD_DESTRUCTOR_ITERATIONS",	_POSIX_THREAD_DESTRUCTOR_ITERATIONS},
#endif
#ifdef _POSIX_THREAD_KEYS_MAX
	{"_POSIX_THREAD_KEYS_MAX",	_POSIX_THREAD_KEYS_MAX},
#endif
#ifdef _POSIX_THREAD_THREADS_MAX
	{"_POSIX_THREAD_THREADS_MAX",	_POSIX_THREAD_THREADS_MAX},
#endif
#ifdef _POSIX_TIMER_MAX
	{"_POSIX_TIMER_MAX",	_POSIX_TIMER_MAX},
#endif
#ifdef _POSIX_TTY_NAME_MAX
	{"_POSIX_TTY_NAME_MAX",	_POSIX_TTY_NAME_MAX},
#endif
#ifdef _POSIX_TZNAME_MAX
	{"_POSIX_TZNAME_MAX",	_POSIX_TZNAME_MAX},
#endif
#ifdef _POSIX2_BC_BASE_MAX
	{"_POSIX2_BC_BASE_MAX",	_POSIX2_BC_BASE_MAX},
#endif
#ifdef _POSIX2_BC_DIM_MAX
	{"_POSIX2_BC_DIM_MAX",	_POSIX2_BC_DIM_MAX},
#endif
#ifdef _POSIX2_BC_SCALE_MAX
	{"_POSIX2_BC_SCALE_MAX",	_POSIX2_BC_SCALE_MAX},
#endif
#ifdef _POSIX2_BC_STRING_MAX
	{"_POSIX2_BC_STRING_MAX",	_POSIX2_BC_STRING_MAX},
#endif
#ifdef _POSIX2_CHARCLASS_NAME_MAX
	{"_POSIX2_CHARCLASS_NAME_MAX",	_POSIX2_CHARCLASS_NAME_MAX},
#endif
#ifdef _POSIX2_COLL_WEIGHTS_MAX
	{"_POSIX2_COLL_WEIGHTS_MAX",	_POSIX2_COLL_WEIGHTS_MAX},
#endif
#ifdef _POSIX2_EXPR_NEST_MAX
	{"_POSIX2_EXPR_NEST_MAX",	_POSIX2_EXPR_NEST_MAX},
#endif
#ifdef _POSIX2_LINE_MAX
	{"_POSIX2_LINE_MAX",	_POSIX2_LINE_MAX},
#endif
#ifdef _POSIX2_RE_DUP_MAX
	{"_POSIX2_RE_DUP_MAX",	_POSIX2_RE_DUP_MAX},
#endif
